// 面板加「打斗」页签（七行动 · 克制链 · 纯前端跑）
const fs = require('fs');
const p = 'src/旮旯给木-英雄坛说/正则/_面板逻辑.js';
let t = fs.readFileSync(p, 'utf8');
if (t.includes('画打斗')) { console.log('（已有）'); process.exit(0); }

const 打斗 = [
  '  /* ════════════════════════════════════════════════════════════',
  '     打斗（七行动 + 克制链）★ 纯前端跑，不花 AI 额度',
  '     机制来自参考项目「姬侠传」——选择决定结果，而不是数值决定',
  '     ════════════════════════════════════════════════════════════ */',
  '  var 战 = null;',
  '',
  '  function 起战(敌名) {',
  '    var t = 算天赋(状态), d = 派生(t, 状态);',
  '    var B = 状态.身体 || {};',
  '    var 我 = {',
  '      名: "我",',
  '      生命: 数(B.生命当前, 100) || 100,',
  '      生命上限: Math.max(1, 数(d.气血上限, 100) || 100),',
  '      气: 0, 挑衅: 0,',
  '      攻击: Math.max(4, Math.round(数(d.攻击力, 20) || 20)),',
  '      格挡: Math.max(0, Math.round(数(d.护甲, 0) || 0)),',
  '    };',
  '    // 敌人按 NPC 战力推档',
  '    var 品 = NPC品级(敌名);',
  '    var 档 = { q0: 8, q1: 14, q2: 22, q3: 34, q4: 50, q5: 70, q6: 90 }[品] || 14;',
  '    var 敌 = {',
  '      名: 敌名 || "来人",',
  '      生命: 档 * 5, 生命上限: 档 * 5, 气: 0, 挑衅: 0,',
  '      攻击: 档, 格挡: Math.round(档 / 4),',
  '    };',
  '    var 风 = ["风", "火", "林", "山"][Math.floor(Math.random() * 4)];',
  '    var 场 = null;',
  '    if (Math.random() < 0.65) {',
  '      var 表 = ((D.战斗与行动 || {}).场地效果) || [];',
  '      if (表.length) 场 = 表[Math.floor(Math.random() * 表.length)];',
  '    }',
  '    战 = { 我: 我, 敌: 敌, 风格: 风, 场地: 场, 回合: 0, 报: [], 完: false };',
  '    画();',
  '  }',
  '',
  '  /* 面板侧的战斗引擎（与机制层同口径 —— 这边是 EJS 跑不了才在前端重写一份小的）*/',
  '  function 战克(a, b) {',
  '    if (a === "嘴炮") {',
  '      if (b === "杀手") return { r: "无效", t: "叫阵打断了他的杀手" };',
  '      if (b === "守势") return { r: "破防", t: "叫阵破了他的守势" };',
  '      return { r: "正常", t: "" };',
  '    }',
  '    if (a === "杀手") {',
  '      if (b === "快招" || b === "沉招") return { r: "无效", t: "杀手压住了他这一招" };',
  '      if (b === "守势") return { r: "无视", t: "杀手破守" };',
  '      return { r: "正常", t: "" };',
  '    }',
  '    if (a === "沉招" && b === "快招") return { r: "无效", t: "沉招压住了快招" };',
  '    if (b === "守势") {',
  '      var 减 = { 快招: 0.15, 沉招: 0.25, 杀手: 1 }[a];',
  '      if (减 == null) return { r: "正常", t: "" };',
  '      if (减 >= 1) return { r: "正常", t: "他在守，但杀手照样吃满" };',
  '      return { r: "减伤", 系: 减, t: "被守住了大半" };',
  '    }',
  '    return { r: "正常", t: "" };',
  '  }',
  '  function 战倍(a) { return ({ 快招: 1, 沉招: 1.5, 杀手: 3 })[a] || 0; }',
  '  function 战气(a) { return ({ 快招: 1, 沉招: 2, 杀手: 5 })[a] || 0; }',
  '  function 出招(我行动) {',
  '    if (!战 || 战.完) return;',
  '    var 我 = 战.我, 敌 = 战.敌, 事 = [];',
  '    // 场地',
  '    var 场 = 战.场地 ? 战.场地.名 : "";',
  '    var 我伤倍 = 1, 敌伤倍 = 1, 自伤 = 0, 禁嘴 = false;',
  '    if (场 === "杀意") { 我伤倍 = 敌伤倍 = 1.5; 自伤 = 0.25; 事.push("杀意：伤害×1.5，攻者也受伤"); }',
  '    if (场 === "气海") { 我.气++; 敌.气++; 事.push("气海：双方 +1 气"); }',
  '    if (场 === "缠斗") { 禁嘴 = true; 事.push("缠斗：不能叫阵"); }',
  '    if (场 === "瘴疠") { var d1 = Math.round(我.生命 * 0.1), d2 = Math.round(敌.生命 * 0.1); 我.生命 = Math.max(0, 我.生命 - d1); 敌.生命 = Math.max(0, 敌.生命 - d2); 事.push("瘴疠：双方各掉 " + d1 + " / " + d2); }',
  '    if (场 === "回春") { 我.生命 = Math.min(我.生命上限, 我.生命 + Math.round(我.生命上限 * 0.1)); 事.push("回春：回血"); }',
  '',
  '    var 我行 = 我行动;',
  '    if (禁嘴 && 我行 === "叫阵") 我行 = "吐纳";',
  '    if (我.挑衅 > 0 && 我行 === "守势") { 我行 = "吐纳"; 事.push("被叫阵，守不住"); }',
  '    if (我.气 < 战气(我行)) { 事.push("气不够，改成吐纳"); 我行 = "吐纳"; }',
  '    else 我.气 -= 战气(我行);',
  '    // 敌人按风格选',
  '    var 偏好 = { 风: ["快招", "叫阵"], 火: ["沉招"], 林: ["吐纳", "杀手"], 山: ["守势"] }[战.风格] || ["快招"];',
  '    var 敌行 = 偏好[Math.floor(Math.random() * 偏好.length)];',
  '    if (敌.气 < 战气(敌行)) 敌行 = 敌.气 >= 1 ? "快招" : "吐纳";',
  '    else 敌.气 -= 战气(敌行);',
  '    if (禁嘴 && 敌行 === "叫阵") 敌行 = "吐纳";',
  '    if (敌.挑衅 > 0 && 敌行 === "守势") 敌行 = "吐纳";',
  '',
  '    if (我行 === "吐纳") { 我.气++; 事.push("我方吐纳，气 +1"); }',
  '    if (敌行 === "吐纳") { 敌.气++; 事.push("对方吐纳，气 +1"); }',
  '    if (我行 === "叫阵" && 敌行 === "守势") { 敌.气 = Math.max(0, 敌.气 - 1); 敌.挑衅 = 2; 事.push("叫阵破了他的守势"); }',
  '    if (敌行 === "叫阵" && 我行 === "守势") { 我.气 = Math.max(0, 我.气 - 1); 我.挑衅 = 2; 事.push("他叫阵破了我方的守势"); }',
  '',
  '    // 我方出手',
  '    var 我倍 = 战倍(我行);',
  '    if (我倍 > 0) {',
  '      var 被压 = 战克(敌行, 我行);',
  '      if (被压.r === "无效") 事.push("我方这一招被压住：" + 被压.t);',
  '      else {',
  '        var 自 = 战克(我行, 敌行);',
  '        var 系 = (自.r === "减伤") ? 自.系 : 1;',
  '        var 伤 = Math.max(1, Math.round((我.攻击 * 我倍 * 我伤倍 - 敌.格挡) * 系));',
  '        敌.生命 = Math.max(0, 敌.生命 - 伤);',
  '        事.push("我方 " + 我行 + " 命中，对方 −" + 伤 + (自.r === "无视" ? "（破守）" : ""));',
  '        if (自伤) { var s = Math.round(伤 * 自伤); 我.生命 = Math.max(0, 我.生命 - s); 事.push("杀意反噬，我方自损 " + s); }',
  '      }',
  '    }',
  '    // 敌方出手',
  '    var 敌倍 = 战倍(敌行);',
  '    if (敌倍 > 0 && 敌.生命 > 0) {',
  '      var 被压2 = 战克(我行, 敌行);',
  '      if (被压2.r === "无效") 事.push("对方这一招被压住：" + 被压2.t);',
  '      else {',
  '        var 自2 = 战克(敌行, 我行);',
  '        var 系2 = (自2.r === "减伤") ? 自2.系 : 1;',
  '        var 伤2 = Math.max(1, Math.round((敌.攻击 * 敌倍 * 敌伤倍 - 我.格挡) * 系2));',
  '        我.生命 = Math.max(0, 我.生命 - 伤2);',
  '        事.push("对方 " + 敌行 + " 命中，我方 −" + 伤2);',
  '        if (自伤) { var s2 = Math.round(伤2 * 自伤); 敌.生命 = Math.max(0, 敌.生命 - s2); 事.push("杀意反噬，对方自损 " + s2); }',
  '      }',
  '    }',
  '    if (我.挑衅 > 0) 我.挑衅--;',
  '    if (敌.挑衅 > 0) 敌.挑衅--;',
  '    战.回合++;',
  '    战.报.unshift("第 " + 战.回合 + " 回合：我方 " + 我行 + " ｜ 对方 " + 敌行 + "　" + 事.join("；"));',
  '    if (战.报.length > 8) 战.报.pop();',
  '    if (我.生命 <= 0 || 敌.生命 <= 0) 战.完 = true;',
  '    // ★ 战斗结果落账（接现有变量）',
  '    if (战.完) {',
  '      写(function (sd) {',
  '        sd.身体 = sd.身体 || {};',
  '        sd.身体.生命当前 = 我.生命;',
  '        sd.战斗临时 = { 结果: 敌.生命 <= 0 ? "我方胜" : "我方败", 回合数: 战.回合,',
  '          我方状态: "剩 " + 我.生命 + "/" + 我.生命上限,',
  '          对方状态: "剩 " + 敌.生命 + "/" + 敌.生命上限,',
  '          存活: (敌.生命 <= 0 ? "我方 1/1　对方 0/1" : "我方 0/1　对方 1/1") };',
  '      });',
  '    }',
  '    画();',
  '  }',
  '  function 取战物() {  /* 道具：简化为回一口血 */',
  '    if (!战 || 战.完) return;',
  '    战.我.生命 = Math.min(战.我.生命上限, 战.我.生命 + Math.round(战.我.生命上限 * 0.3));',
  '    战.报.unshift("取物：服了一剂，回 " + Math.round(战.我.生命上限 * 0.3) + " 血");',
  '    画();',
  '  }',
  '',
  '  function 画打斗() {',
  '    var 行表 = ((D.战斗与行动 || {}).我方行动命名) || { 集气: "吐纳", 防御: "守势", 轻攻击: "快招", 重攻击: "沉招", 绝招: "杀手", 嘴炮: "叫阵", 道具: "取物" };',
  '    var 序 = ["集气", "防御", "轻攻击", "重攻击", "绝招", "嘴炮", "道具"];',
  '    var H = "";',
  '    if (!战) {',
  '      // 选对手',
  '      var 地点 = (状态.场景 || {}).当前地点 || "";',
  '      var 在场 = Object.keys(D.NPC || {}).filter(function (n) {',
  '        var w = String((D.NPC[n] || {}).所在 || "");',
  '        return 地点 && w.indexOf(地点.slice(0, 3)) >= 0;',
  '      }).slice(0, 8);',
  '      H += \'<div class="yx-r"><div class="yx-c yx-w"><div class="yx-ttl">打斗 <em>（七行动 · 克制链 · 纯前端跑）</em></div>\';',
  '      H += \'<div class="yx-nt">选一个人动手。战斗逐回合真跑，同一局面结果一致；打完后结果会写进「上一场」，也会落到正文里。</div>\';',
  '      if (!在场.length) H += \'<div class="yx-e">这一带没有可交战的人。</div>\';',
  '      else H += \'<div class="yx-foes" style="margin-top:10px">\' + 在场.map(function (n) {',
  '        var 品 = NPC品级(n), 色 = 档色(品);',
  '        return \'<button class="yx-btn" data-开打="\' + E(n) + \'" style="border-color:\' + 色 + \'66;color:\' + 色 + \'">\' + E(n) + "　" + 品名(品) + "</button>";',
  '      }).join("") + "</div>";',
  '      H += "</div></div>";',
  '      return H;',
  '    }',
  '    var 我 = 战.我, 敌 = 战.敌;',
  '    H += \'<div class="yx-r"><div class="yx-c yx-w"><div class="yx-ttl">打斗 <em>第 \' + 战.回合 + " 回合</em></div>";',
  '    H += \'<div class="yx-bw"><span class="lb">我方</span><div class="yx-bar"><i class="hp" style="width:\' + (我.生命 / 我.生命上限 * 100) + \'%"></i></div><span class="vl">\' + 我.生命 + "/" + 我.生命上限 + "　气 " + 我.气 + \'</span></div>\';',
  '    H += \'<div class="yx-bw"><span class="lb">\' + E(敌.名) + \'</span><div class="yx-bar"><i style="width:\' + (敌.生命 / 敌.生命上限 * 100) + \'%;background:#e05a4a"></i></div><span class="vl">\' + 敌.生命 + "/" + 敌.生命上限 + "　气 " + 敌.气 + \'</span></div>\';',
  '    var 风色 = { 风: "#5ca3d8", 火: "#e05a4a", 林: "#4f8f6b", 山: "#c69c6d" }[战.风格];',
  '    H += \'<div class="yx-nt">对方风格 <b style="color:\' + 风色 + \'">\' + E(战.风格) + \'</b>（\u8bfb\u5bf9\u624b\uff1a\u98ce\u5feb\u653b\u3001\u706b\u7206\u53d1\u3001\u6797\u84c4\u529b\u3001\u5c71\u5b88\uff09\' + (战.场地 ? \'　\u573a\u5730 <b>\' + E(战.场地.标 + 战.场地.名) + "</b>" : "") + "</div>";',
  '    if (战.场地) H += \'<div class="yx-nt">\' + E(战.场地.效果) + "</div>";',
  '    if (!战.完) {',
  '      H += \'<div class="yx-foes" style="margin-top:11px">\' + 序.map(function (k) {',
  '        var 耗 = 战气(k);',
  '        var 能 = (我.气 >= 耗);',
  '        return \'<button class="yx-btn" data-出招="\' + k + \'"\' + (能 ? "" : " disabled") + \' title="\u8017\u6c14 \' + 耗 + \'">\' + E(行表[k] || k) + (耗 ? " (" + 耗 + ")" : "") + "</button>";',
  '      }).join("") + "</div>";',
  '      H += \'<div class="yx-nt">杀手 5 气无视防御；守势挡快招只吃 15%；叫阵破守势、制杀手</div>\';',
  '    } else {',
  '      H += \'<div class="yx-foes" style="margin-top:11px"><span class="yx-ch \' + (敌.生命 <= 0 ? "on" : "rd") + \'">\' + (敌.生命 <= 0 ? "我方胜" : "我方败") + \'</span></div>\';',
  '      H += \'<div class="yx-ops" style="margin-top:10px"><button class="yx-btn pri" id="yx-zs">再打一场</button><button class="yx-btn" id="yx-bz">收手</button></div>\';',
  '    }',
  '    if (战.报.length) H += \'<div class="yx-k2">战报</div>\' + 战.报.map(function (x) { return \'<div class="yx-nt">\' + E(x) + "</div>"; }).join("");',
  '    H += "</div></div>";',
  '    return H;',
  '  }',
  '',
].join('\n');

t = t.replace('  /* ── 说明 ── */', 打斗 + '  /* ── 说明 ── */');

// 页签 + 分支 + 绑定
t = t.replace('{ id: "dan", 名: "丹房" },', '{ id: "dan", 名: "丹房" },\n    { id: "fight", 名: "打斗" },');
t = t.replace("    else if (页 === 'dan') { 体.innerHTML = 画丹房(); 绑丹房(); return; }",
  "    else if (页 === 'dan') { 体.innerHTML = 画丹房(); 绑丹房(); return; }\n    else if (页 === 'fight') { 体.innerHTML = 画打斗(); 绑打斗(); return; }");
t = t.replace('  /* ── 说明 ── */', [
  '  function 绑打斗() {',
  '    [].forEach.call(document.querySelectorAll("[data-开打]"), function (b) {',
  '      b.addEventListener("click", function () { 起战(b.getAttribute("data-开打")); });',
  '    });',
  '    [].forEach.call(document.querySelectorAll("[data-出招]"), function (b) {',
  '      b.addEventListener("click", function () {',
  '        var k = b.getAttribute("data-出招");',
  '        if (k === "道具") 取战物(); else 出招(k);',
  '      });',
  '    });',
  '    var a = document.getElementById("yx-zs"); if (a) a.addEventListener("click", function () { 战 = null; 画(); });',
  '    var b2 = document.getElementById("yx-bz"); if (b2) b2.addEventListener("click", function () { 战 = null; 画(); });',
  '  }',
  '',
  '  /* ── 说明 ── */',
].join('\n'));

fs.writeFileSync(p, t);
console.log('✅ 打斗页签已加（' + Math.round(Buffer.byteLength(t, 'utf8') / 1024) + ' KB）');

// 生成器带上 战斗与行动
const gp = 'src/旮旯给木-英雄坛说/scripts/gen-panel.cjs';
let g = fs.readFileSync(gp, 'utf8');
if (!g.includes('战斗与行动')) {
  g = g.replace("  日常与资源: 读(path.join(契约, '日常与资源.yaml'), {}),",
    "  日常与资源: 读(path.join(契约, '日常与资源.yaml'), {}),\n  战斗与行动: 读(path.join(契约, '战斗与行动.yaml'), {}),");
  fs.writeFileSync(gp, g);
  console.log('✅ 生成器带上 战斗与行动');
}
