// 霍格沃茨 · 同层卡 MVU 变量结构（zod 4）
// 对齐参考：
//   - 战斗/双修字段 → fanren-remake 斗法台/双修面板（修为进度/情欲/快感/堕落/顺从/主导方/动作编排/物品/体位/裁决/回溯/品质）
//   - 角色档案/性癖 → 相亲模拟器（性格/性癖标签条目化 + 调度器 getwi 按需加载 + 每角色独立标签组合）
//   - 排班/生理/身体状态 → 欲望都市（面板本地结算、对偶维度、生理周期）
//   - 成长体系 → fanren 境界（9 大境界 27 层魔力阶位 + 突破/瓶颈/心魔/材料品级/装备）
// 铁律：面板/脚本写数值，AI 只读并叙事；stat_data 是唯一事实源；结算块是事实传递

export const Schema = z.object({
  时间: z.object({
    日期: z.string().prefault('1991年9月1日'),
    星期: z.string().prefault('星期一'),
    时段: z.enum(['上午', '下午', '晚间', '深夜']).prefault('上午'),
    学年: z.coerce.number().transform(v => _.clamp(v, 1, 7)).prefault(5).describe('学年 1~7：学年路由按此 getwi 对应学年剧情条目'),
    学期: z.enum(['第一学期', '第二学期', '假期']).prefault('第一学期'),
    学期描述: z.string().prefault('五年级·第一学期'),
  }).prefault({ 日期: '1991年9月1日', 星期: '星期一', 时段: '上午', 学年: 5, 学期: '第一学期', 学期描述: '五年级·第一学期' }),

  玩家: z.object({
    学业: z.object({
      年级: z.coerce.number().transform(v => _.clamp(v, 1, 7)).prefault(5),
      学院: z.enum(['格兰芬多', '斯莱特林', '拉文克劳', '赫奇帕奇']).prefault('格兰芬多'),
      血统: z.enum(['纯血', '混血', '麻瓜出身']).prefault('混血'),
      各科: z.object({
        魔咒学: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(82),
        变形术: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(75),
        黑魔法防御术: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(88),
        魔药学: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(70),
        草药学: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(65),
        天文学: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(72),
        魔法史: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(60),
      }).prefault({ 魔咒学: 82, 变形术: 75, 黑魔法防御术: 88, 魔药学: 70, 草药学: 65, 天文学: 72, 魔法史: 60 }),
      学业总分: z.preprocess(v => Array.isArray(v) ? Number(v[0]) : v, z.coerce.number().transform(v => _.clamp(v, 0, 700))).prefault(512),
    }).prefault({ 年级: 5, 学院: '格兰芬多', 血统: '混血', 各科: { 魔咒学: 82, 变形术: 75, 黑魔法防御术: 88, 魔药学: 70, 草药学: 65, 天文学: 72, 魔法史: 60 }, 学业总分: 512 }),
    属性: z.object({
      体力: z.preprocess(v => Array.isArray(v) ? Number(v[0]) : v, z.coerce.number().transform(v => _.clamp(v, 0, 100))).prefault(80),
      魔力值: z.preprocess(v => Array.isArray(v) ? Number(v[0]) : v, z.coerce.number().transform(v => _.clamp(v, 0, 9999))).prefault(76).describe('魔力值（0~9999）：由魔力阶位层阈值划分区间；双修结算+2~8、冥想/过夜+20；达标+条件满足=可突破'),
      魔法感知: z.preprocess(v => Array.isArray(v) ? Number(v[0]) : v, z.coerce.number().transform(v => _.clamp(v, 0, 100))).prefault(60).describe('对异性的敏锐度：影响被撩拨时的先手与察觉，阶位天赋可加成'),
    }).prefault({ 体力: 80, 魔力值: 76, 魔法感知: 60 }),
    魔力阶位: z.object({
      大境界: z.coerce.number().transform(v => _.clamp(v, 1, 9)).prefault(1).describe('1~9：初醒/凝聚/贯通/掌控/精纯/结晶/化形/领域/本源'),
      层: z.coerce.number().transform(v => _.clamp(v, 1, 3)).prefault(1).describe('1~3：初期/中期/后期'),
      层进度: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(0).describe('当前层修炼进度 0~100，战斗胜/双修/学业推进，满100且条件满足可突破'),
      突破进度: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(0).describe('突破准备进度：材料/魔药/仪式准备程度，100=可尝试突破'),
      心魔状态: z.enum(['无', '待突破', '突破中', '心魔期']).prefault('无').describe('突破时进入心魔期：AI 按对应阶位条目演出心魔剧情，突破完成后清除'),
      突破记录: z.array(z.object({
        日期: z.string().prefault(''),
        从: z.string().prefault('').describe('如 初醒·初期'),
        到: z.string().prefault('').describe('如 初醒·中期'),
        心魔: z.string().prefault('').describe('本次心魔类型'),
      }).prefault({ 日期: '', 从: '', 到: '', 心魔: '' })).prefault([]),
    }).prefault({ 大境界: 1, 层: 1, 层进度: 0, 突破进度: 0, 心魔状态: '无', 突破记录: [] }),
    状态: z.object({
      情欲: z.preprocess(v => Array.isArray(v) ? Number(v[0]) : v, z.coerce.number().transform(v => _.clamp(v, 0, 100))).prefault(30).describe('0~100，<20 无法勃起=唯一拒战途径'),
      快感: z.preprocess(v => Array.isArray(v) ? Number(v[0]) : v, z.coerce.number().transform(v => _.clamp(v, 0, 100))).prefault(10).describe('受情欲上限约束，≥60 可射精'),
    }).prefault({ 情欲: 30, 快感: 10 }),
    咒语: z.object({
      昏昏倒地: z.object({ 等级: z.coerce.number().transform(v => _.clamp(v, 1, 20)).prefault(1), 经验: z.coerce.number().transform(v => _.clamp(v, 0, 9999)).prefault(0) }).prefault({ 等级: 1, 经验: 0 }).describe('直击：Lv×3 伤害，每回合麻痒点+2；麻痒≥5 她失神（防守值-5）'),
      火焰熊熊: z.object({ 等级: z.coerce.number().transform(v => _.clamp(v, 1, 20)).prefault(1), 经验: z.coerce.number().transform(v => _.clamp(v, 0, 9999)).prefault(0) }).prefault({ 等级: 1, 经验: 0 }).describe('灼热：Lv×2 伤害，她本回合减伤-1（可叠加）'),
      摄神取念: z.object({ 等级: z.coerce.number().transform(v => _.clamp(v, 1, 20)).prefault(1), 经验: z.coerce.number().transform(v => _.clamp(v, 0, 9999)).prefault(0) }).prefault({ 等级: 1, 经验: 0 }).describe('精神渗透：Lv×1 伤害，她敏感度×(1+Lv×0.1)，配合麻痒类效果该技能伤害×2'),
      统统石化: z.object({ 等级: z.coerce.number().transform(v => _.clamp(v, 1, 20)).prefault(1), 经验: z.coerce.number().transform(v => _.clamp(v, 0, 9999)).prefault(0) }).prefault({ 等级: 1, 经验: 0 }).describe('僵直：Lv×2.5 伤害，她的"绞缠/收缩"类减伤减半'),
      厉火咒: z.object({ 等级: z.coerce.number().transform(v => _.clamp(v, 1, 20)).prefault(1), 经验: z.coerce.number().transform(v => _.clamp(v, 0, 9999)).prefault(0) }).prefault({ 等级: 1, 经验: 0 }).describe('炽焰：Lv×4 伤害，寒系名器伤害×2'),
      粉身碎骨: z.object({ 等级: z.coerce.number().transform(v => _.clamp(v, 1, 20)).prefault(1), 经验: z.coerce.number().transform(v => _.clamp(v, 0, 9999)).prefault(0) }).prefault({ 等级: 1, 经验: 0 }).describe('连击：Lv×2 伤害，本回合最终伤害×1.5'),
      万弹齐发: z.object({ 等级: z.coerce.number().transform(v => _.clamp(v, 1, 20)).prefault(1), 经验: z.coerce.number().transform(v => _.clamp(v, 0, 9999)).prefault(0) }).prefault({ 等级: 1, 经验: 0 }).describe('频射：Lv×2 伤害，频率 Lv×10 次/分；超过她承受阈值她减伤-1/回合'),
    }).prefault({ 昏昏倒地: { 等级: 1, 经验: 0 }, 火焰熊熊: { 等级: 1, 经验: 0 }, 摄神取念: { 等级: 1, 经验: 0 }, 统统石化: { 等级: 1, 经验: 0 }, 厉火咒: { 等级: 1, 经验: 0 }, 粉身碎骨: { 等级: 1, 经验: 0 }, 万弹齐发: { 等级: 1, 经验: 0 } }),
    魔咒库: z.record(z.string().describe('扩展咒语名（课程/禁书解锁，如 盔甲护身/速速禁锢/愈合如初/幻身咒）'), z.object({
      等级: z.coerce.number().transform(v => _.clamp(v, 1, 20)).prefault(1),
      经验: z.coerce.number().transform(v => _.clamp(v, 0, 9999)).prefault(0),
    }).prefault({ 等级: 1, 经验: 0 })).prefault({}).describe('扩展魔咒库：按年级/课程/阶位解锁，战斗面板可选技能池'),
    装备: z.object({
      魔杖: z.object({
        名: z.string().prefault('冬青木魔杖'),
        材质: z.string().prefault('冬青木').describe('木材：冬青/紫杉/接骨木/橡木/樱桃木/山毛榉…'),
        杖芯: z.string().prefault('凤凰尾羽').describe('杖芯：凤凰尾羽/龙心弦/独角兽毛/夜骐尾羽/媚娃头发…'),
        品级: z.enum(['普通', '精良', '稀有', '传说', '神话']).prefault('普通').describe('品级限制阶位发挥：普通魔杖最高撑到贯通，传说才能发挥结晶+'),
      }).prefault({ 名: '冬青木魔杖', 材质: '冬青木', 杖芯: '凤凰尾羽', 品级: '普通' }),
      巫师袍: z.object({
        名: z.string().prefault('校服巫师袍'),
        品级: z.enum(['普通', '精良', '稀有', '传说', '神话']).prefault('普通').describe('防护/舒适加成，战斗面板自动应用'),
      }).prefault({ 名: '校服巫师袍', 品级: '普通' }),
      饰品: z.record(z.string().describe('饰品名（如 防护挂坠/福灵吊坠）'), z.enum(['普通', '精良', '稀有', '传说', '神话']).prefault('普通')).prefault({}),
    }).prefault({ 魔杖: { 名: '冬青木魔杖', 材质: '冬青木', 杖芯: '凤凰尾羽', 品级: '普通' }, 巫师袍: { 名: '校服巫师袍', 品级: '普通' }, 饰品: {} }),
    材料: z.record(z.string().describe('材料名（如 白鲜根/月光草/曼德拉草/龙血/凤凰泪）'), z.object({
      数量: z.coerce.number().transform(v => _.clamp(v, 0, 999)).prefault(0),
      品级: z.enum(['普通', '精良', '稀有', '传说', '神话']).prefault('普通'),
    }).prefault({ 数量: 0, 品级: '普通' })).prefault({}).describe('突破/魔药材料：品级决定可用途（突破仪式/熬制魔药/交易）'),
    财产: z.object({
      金加隆: z.coerce.number().transform(v => _.clamp(v, 0, 99999)).prefault(20).describe('1 金加隆 = 17 西可 = 493 纳特'),
      西可: z.coerce.number().transform(v => _.clamp(v, 0, 999)).prefault(0),
      纳特: z.coerce.number().transform(v => _.clamp(v, 0, 999)).prefault(0),
    }).prefault({ 金加隆: 20, 西可: 0, 纳特: 0 }),
    魔药: z.object({
      福灵剂: z.coerce.number().transform(v => _.clamp(v, 0, 99)).prefault(0).describe('下一场对抗全属性小幅提升（面板自动应用：伤害+2、反击-1）'),
      迷情剂: z.coerce.number().transform(v => _.clamp(v, 0, 99)).prefault(0).describe('双修中对方情欲+30（一次性）'),
      复方汤剂: z.coerce.number().transform(v => _.clamp(v, 0, 99)).prefault(0).describe('叙事道具，伪装身份用'),
      欢欣剂: z.coerce.number().transform(v => _.clamp(v, 0, 99)).prefault(1).describe('情欲+40'),
      润滑魔油: z.coerce.number().transform(v => _.clamp(v, 0, 99)).prefault(2).describe('双修中对方快感+20（一次性）'),
      安神药剂: z.coerce.number().transform(v => _.clamp(v, 0, 99)).prefault(1).describe('双修后魔力值恢复+15'),
      突破魔药: z.coerce.number().transform(v => _.clamp(v, 0, 99)).prefault(0).describe('突破必需：按阶位品级要求消耗（初醒~凝聚=普通，贯通~掌控=精良，精纯~结晶=稀有，化形~领域=传说，本源=神话）'),
    }).prefault({ 福灵剂: 0, 迷情剂: 0, 复方汤剂: 0, 欢欣剂: 1, 润滑魔油: 2, 安神药剂: 1, 突破魔药: 0 }),
    战绩: z.object({
      今日胜场: z.coerce.number().transform(v => _.clamp(v, 0, 99)).prefault(0),
      今日败场: z.coerce.number().transform(v => _.clamp(v, 0, 99)).prefault(0),
      累计缴械: z.coerce.number().transform(v => _.clamp(v, 0, 999)).prefault(0).describe('决斗中你缴械对方（魔杖脱手获胜）累计次数'),
      累计被缴械: z.coerce.number().transform(v => _.clamp(v, 0, 999)).prefault(0).describe('你的决斗败绩累计次数（纯战绩记录）'),
      决斗荣誉: z.coerce.number().transform(v => _.clamp(v, 0, 99999)).prefault(0).describe('决斗胜场累积的荣誉值，决斗俱乐部排名依据'),
    }).prefault({ 今日胜场: 0, 今日败场: 0, 累计缴械: 0, 累计被缴械: 0, 决斗荣誉: 0 }),
    胜点: z.coerce.number().transform(v => _.clamp(v, 0, 9999)).prefault(0).describe('念头植入货币：决斗胜利+5~15、完全缴械+20、突破+30；消耗胜点向女巫植入性癖念头（见【胜点与念头植入规则】）'),
    文风强度: z.coerce.number().transform(v => _.clamp(v, 1, 3)).prefault(2).describe('淫秽文风强度（设置1-3，默认2）：亲密/改造场景的描写露骨度上限，见【淫秽文风与描写规范】'),
    文风气质: z.enum(['自动', '淫荡露骨', '高冷反差', '清纯羞涩', '成熟挑逗', '直白运动', '病娇独占']).prefault('自动').describe('淫秽文风气质（默认自动=按她性格标签匹配）：骚有千万种，母猪风只是淫荡露骨型的极端，见【淫秽文风与描写规范v2】'),
    植入记录: z.array(z.looseObject({}).describe('一次念头植入：{ 目标, 性癖, 消耗, 契合度, 成功率, 植入日期, 预计生效日, 阶段, 评价 }')).prefault([]).describe('念头植入历史与进行中状态（潜伏→萌芽→生效）'),
    炼药: z.object({
      熟练度: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(0).describe('炼药成功率修正：每炉+5（失败+2）'),
    }).prefault({ 熟练度: 0 }),
    生理: z.object({
      今日射精次数: z.coerce.number().transform(v => _.clamp(v, 0, 99)).prefault(0),
      射精冷却剩余: z.coerce.number().transform(v => _.clamp(v, 0, 24)).prefault(0),
      最后射精日期: z.string().prefault(''),
      晨勃: z.boolean().prefault(true),
      上次恢复体力日期: z.string().prefault(''),
      上次推进日期: z.string().prefault(''),
    }).prefault({ 今日射精次数: 0, 射精冷却剩余: 0, 最后射精日期: '', 晨勃: true, 上次恢复体力日期: '', 上次推进日期: '' }),
    记忆: z.object({
      长期档案: z.object({
        small_summary: z.string().prefault('').describe('长期记忆详细档案（200-500字）：重要人物/关系/约定/关键物品/伏笔，记忆整合时由 AI 生成'),
        large_summary: z.string().prefault('').describe('长期记忆精简索引（50-100字）：用于快速回顾，随剧情推进滚动更新'),
        更新时间: z.string().prefault(''),
      }).prefault({ small_summary: '', large_summary: '', 更新时间: '' }),
      世界推演报告: z.array(z.object({
        时间: z.string().prefault(''),
        内容: z.string().prefault('').describe('推演报告摘要（明线/暗线/女巫行动），叙事 AI 应沿此推进'),
      }).prefault({ 时间: '', 内容: '' })).prefault([]).describe('历次世界推演报告（保留最近 3 条）：注入 AI 提示词作为剧情指导'),
    }).prefault({ 长期档案: { small_summary: '', large_summary: '', 更新时间: '' }, 世界推演报告: [] }),
    特质: z.string().prefault('').describe('玩家天赋/特质：开局引导选择（如 魔力亲和/运动健将），影响初始数值与叙事设定'),
    副API配置: z.looseObject({}).optional(),
  }).prefault({ 学业: { 年级: 5, 学院: '格兰芬多', 血统: '混血', 各科: { 魔咒学: 82, 变形术: 75, 黑魔法防御术: 88, 魔药学: 70, 草药学: 65, 天文学: 72, 魔法史: 60 }, 学业总分: 512 }, 属性: { 体力: 80, 魔力值: 76, 魔法感知: 60 }, 魔力阶位: { 大境界: 1, 层: 1, 层进度: 0, 突破进度: 0, 心魔状态: '无', 突破记录: [] }, 状态: { 情欲: 30, 快感: 10 }, 咒语: { 昏昏倒地: { 等级: 1, 经验: 0 }, 火焰熊熊: { 等级: 1, 经验: 0 }, 摄神取念: { 等级: 1, 经验: 0 }, 统统石化: { 等级: 1, 经验: 0 }, 厉火咒: { 等级: 1, 经验: 0 }, 粉身碎骨: { 等级: 1, 经验: 0 }, 万弹齐发: { 等级: 1, 经验: 0 } }, 魔咒库: {}, 装备: { 魔杖: { 名: '冬青木魔杖', 材质: '冬青木', 杖芯: '凤凰尾羽', 品级: '普通' }, 巫师袍: { 名: '校服巫师袍', 品级: '普通' }, 饰品: {} }, 材料: {}, 财产: { 金加隆: 20, 西可: 0, 纳特: 0 }, 魔药: { 福灵剂: 0, 迷情剂: 0, 复方汤剂: 0, 欢欣剂: 1, 润滑魔油: 2, 安神药剂: 1, 突破魔药: 0 }, 战绩: { 今日胜场: 0, 今日败场: 0, 累计缴械: 0, 累计被缴械: 0 }, 生理: { 今日射精次数: 0, 射精冷却剩余: 0, 最后射精日期: '', 晨勃: true, 上次恢复体力日期: '', 上次推进日期: '' }, 记忆: { 长期档案: { small_summary: '', large_summary: '', 更新时间: '' }, 世界推演报告: [] }, 特质: '' }),

  课表: z.object({
    今日场次: z.record(z.string().describe('时段'), z.object({
      参与者: z.string().prefault(''),
      结果: z.string().prefault('未开战').describe('未开战/你胜/你败/拒战/双修'),
      是否参战: z.boolean().prefault(false),
    }).prefault({ 参与者: '', 结果: '未开战', 是否参战: false })).prefault({}),
    当前目标: z.string().prefault('').describe('当前对抗/约会目标（女巫姓名），人设路由/学年路由按此调度'),
    战斗状态: z.enum(['未开始', '进行中', '已结算']).prefault('未开始'),
    战斗: z.object({
      回合: z.coerce.number().transform(v => _.clamp(v, 0, 99)).prefault(0),
      主角防守值: z.coerce.number().transform(v => _.clamp(v, 0, 999)).prefault(96).describe('你的防守值（=开战瞬间体力×1.2×阶位系数），归零=你被缴械败北'),
      主角防守值上限: z.coerce.number().transform(v => _.clamp(v, 0, 999)).prefault(96),
      她防守值: z.coerce.number().transform(v => _.clamp(v, 0, 999)).prefault(44).describe('她的防守值，归零=她缴械（你胜）'),
      她防守值上限: z.coerce.number().transform(v => _.clamp(v, 0, 999)).prefault(44),
      麻痒点: z.coerce.number().transform(v => _.clamp(v, 0, 99)).prefault(0).describe('叠加在她身上的刺激累积，≥5 她失神'),
      主角麻痒点: z.coerce.number().transform(v => _.clamp(v, 0, 99)).prefault(0),
      她减伤修正: z.coerce.number().transform(v => _.clamp(v, -20, 20)).prefault(0),
      目标列表: z.array(z.string()).prefault([]).describe('多人对抗参与者姓名数组'),
      目标防守值: z.record(z.string(), z.coerce.number()).prefault({}).describe('多人对抗各参与者当前防守值'),
      本场经验: z.record(z.string(), z.coerce.number()).prefault({}).describe('本场各咒语获得经验'),
      主角BUFF: z.record(z.string().describe('BUFF名'), z.object({
        剩余回合: z.coerce.number().transform(v => _.clamp(v, 0, 10)).prefault(0),
        效果值: z.coerce.number().transform(v => _.clamp(v, -20, 20)).prefault(0),
      }).prefault({ 剩余回合: 0, 效果值: 0 })).prefault({}),
      她BUFF: z.record(z.string().describe('BUFF名'), z.object({
        剩余回合: z.coerce.number().transform(v => _.clamp(v, 0, 10)).prefault(0),
        效果值: z.coerce.number().transform(v => _.clamp(v, -20, 20)).prefault(0),
      }).prefault({ 剩余回合: 0, 效果值: 0 })).prefault({}),
    }).prefault({ 回合: 0, 主角防守值: 96, 主角防守值上限: 96, 她防守值: 44, 她防守值上限: 44, 麻痒点: 0, 主角麻痒点: 0, 她减伤修正: 0, 目标列表: [], 目标防守值: {}, 本场经验: {}, 主角BUFF: {}, 她BUFF: {} }),
  }).prefault({ 今日场次: {}, 当前目标: '', 战斗状态: '未开始', 战斗: { 回合: 0, 主角防守值: 96, 主角防守值上限: 96, 她防守值: 44, 她防守值上限: 44, 麻痒点: 0, 主角麻痒点: 0, 她减伤修正: 0, 目标列表: [], 目标防守值: {}, 本场经验: {}, 主角BUFF: {}, 她BUFF: {} } }),

  双修: z.object({
    会话状态: z.enum(['未开始', '进行中', '裁决中', '已结束']).prefault('未开始').describe('对应双修会话：进行中=每轮动作裁决；裁决中=等待AI结算写回；已结束=结算完成'),
    对象: z.string().prefault('').describe('本次双修对象（女巫姓名）'),
    主导方: z.enum(['我来', '对方来']).prefault('我来').describe('对应双修 我来/对方来'),
    当前体位: z.string().prefault('尚未明确'),
    本轮动作: z.array(z.object({
      行为: z.string().prefault(''),
      部位: z.string().prefault(''),
      风格: z.string().prefault(''),
    }).prefault({ 行为: '', 部位: '', 风格: '' })).prefault([]).describe('动作编排（最多3组）：行为+部位+风格'),
    使用物品: z.string().prefault('不使用物品'),
    修为进度: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(0).describe('对应双修 修为进度：本场累积的修为，结算时折算为魔力值成长'),
    情欲: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(0),
    快感: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(0).describe('满 100 触发高潮'),
    堕落: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(0).describe('本场堕落度（对应双修 堕落），结算时折算她的堕落值成长'),
    顺从: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(0).describe('本场顺从度（对应双修 顺从），决定结算品质'),
    高潮待宣: z.boolean().prefault(false).describe('对应双修 灵机待宣：快感已满、等待AI在正文中宣布高潮'),
    快感清零: z.boolean().prefault(false).describe('对应双修 快感清零：宣布高潮后本场快感归零'),
    下轮高潮: z.boolean().prefault(false).describe('对应双修 下轮高潮：预告下一轮将触发高潮'),
    裁决状态: z.enum(['等待触发', '裁决中', '已完成']).prefault('等待触发'),
    可回溯: z.boolean().prefault(false).describe('对应双修 回溯：结算前可撤销本轮动作'),
    历史轮: z.array(z.object({
      轮次: z.coerce.number().prefault(0),
      动作: z.string().prefault(''),
      结果: z.string().prefault('').describe('品质：无效/低效/普通/上佳'),
      修为进度: z.coerce.number().prefault(0),
      快感变化: z.coerce.number().prefault(0),
      堕落变化: z.coerce.number().prefault(0),
      顺从变化: z.coerce.number().prefault(0),
    }).prefault({ 轮次: 0, 动作: '', 结果: '', 修为进度: 0, 快感变化: 0, 堕落变化: 0, 顺从变化: 0 })).prefault([]),
  }).prefault({ 会话状态: '未开始', 对象: '', 主导方: '我来', 当前体位: '尚未明确', 本轮动作: [], 使用物品: '不使用物品', 修为进度: 0, 情欲: 0, 快感: 0, 堕落: 0, 顺从: 0, 高潮待宣: false, 快感清零: false, 下轮高潮: false, 裁决状态: '等待触发', 可回溯: false, 历史轮: [] }),

  女巫角色: z.record(z.string().describe('角色名'), z.object({
    身份: z.string().prefault(''),
    学院: z.enum(['格兰芬多', '斯莱特林', '拉文克劳', '赫奇帕奇', '教授团']).prefault('格兰芬多'),
    血统: z.enum(['纯血', '混血', '麻瓜出身']).prefault('混血'),
    年级: z.string().prefault('').describe('年级或职位'),
    性格标签: z.array(z.string()).prefault([]).describe('性格标签数组 2~3 个（如 ["傲娇型","大小姐型"]），人设路由 getwi 逐个加载对应条目'),
    性癖标签: z.array(z.string()).prefault([]).describe('性癖标签数组 4~5 个（如 ["反差婊","口嫌体正直","调教"]），人设路由 getwi 逐个加载'),
    秘密: z.string().prefault('').describe('她隐藏的秘密，构成角色张力，随剧情/堕落值阶段揭晓'),
    口癖: z.string().prefault(''),
    关系: z.string().prefault(''),
    好感度: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(5).describe('社交好感（独立于缴械值/堕落值）：性格标签 13 阶段调度轴'),
    缴械值: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(0).describe('对抗胜负线：100=完全缴械（永久），战斗中升降'),
    堕落值: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(0).describe('心理沉沦线（双修结算成长）：越高越放得开，≥100=完全堕落（随时可召唤）'),
    缴械次数: z.coerce.number().transform(v => _.clamp(v, 0, 999)).prefault(0),
    战斗次数: z.coerce.number().transform(v => _.clamp(v, 0, 999)).prefault(0),
    胜场: z.coerce.number().transform(v => _.clamp(v, 0, 999)).prefault(0),
    败场: z.coerce.number().transform(v => _.clamp(v, 0, 999)).prefault(0),
    名器: z.string().prefault('').describe('名器（私密特性名）'),
    名器防御: z.coerce.number().transform(v => _.clamp(v, 0, 10)).prefault(6),
    防守值上限: z.coerce.number().transform(v => _.clamp(v, 0, 999)).prefault(44).describe('身份基础+名器防御×2+主技能等级×4'),
    技能: z.object({
      名: z.string().prefault('').describe('她的主技能（性技/体质技）'),
      等级: z.coerce.number().transform(v => _.clamp(v, 1, 20)).prefault(1),
      经验: z.coerce.number().transform(v => _.clamp(v, 0, 9999)).prefault(0),
      技能组: z.record(z.string().describe('辅技能名'), z.object({
        等级: z.coerce.number().transform(v => _.clamp(v, 1, 20)).prefault(1),
        经验: z.coerce.number().transform(v => _.clamp(v, 0, 9999)).prefault(0),
      }).prefault({ 等级: 1, 经验: 0 })).prefault({}),
    }).prefault({ 名: '', 等级: 1, 经验: 0, 技能组: {} }),
    能力值: z.object({
      忍耐: z.coerce.number().transform(v => _.clamp(v, 1, 10)).prefault(5),
      持久: z.coerce.number().transform(v => _.clamp(v, 1, 10)).prefault(5),
      反攻: z.coerce.number().transform(v => _.clamp(v, 1, 10)).prefault(5),
    }).prefault({ 忍耐: 5, 持久: 5, 反攻: 5 }),
    特质: z.string().prefault(''),
    缺陷: z.string().prefault(''),
    欲望积压: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(0).describe('欲望积压：越高越容易主动、防守越脆、反击越凶'),
    压力值: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(50).describe('她自己的生活压力（学业/家族/职业），驱动欲望积压增长'),
    是否缴械: z.boolean().prefault(false).describe('她已承认你在决斗上彻底强于她（缴械值100，永久）'),
    缴械日期: z.string().prefault(''),
    高潮次数: z.coerce.number().transform(v => _.clamp(v, 0, 999)).prefault(0).describe('与你的亲密高潮累计次数：身体敏感化长期积累依据'),
    信任裂痕: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(0).describe('信任损伤：背叛/冷落累积，>0 时好感上升减速（阶段降过需额外+10好感弥补）'),
    被植入念头: z.array(z.looseObject({}).describe('被植入的性癖念头：{ 性癖, 阶段: 潜伏|萌芽|生效, 植入日期, 预计生效日, 契合度, 成功率, 来源 }')).prefault([]).describe('胜点植入的念头：潜伏（标签入库不触发）→萌芽（低欲望触发）→生效（完全激活，并入性癖标签数组）'),
    今日已使用: z.boolean().prefault(false),
    道具栏: z.record(z.string().describe('道具名'), z.coerce.number().transform(v => _.clamp(v, 0, 99)).prefault(0)).prefault({}),
    恢复技能: z.object({
      名: z.string().prefault(''),
      等级: z.coerce.number().transform(v => _.clamp(v, 1, 20)).prefault(1),
      经验: z.coerce.number().transform(v => _.clamp(v, 0, 9999)).prefault(0),
    }).prefault({ 名: '', 等级: 1, 经验: 0 }),
    服装: z.record(z.string().describe('部位'), z.string().prefault('')).prefault({}),
    身体状态: z.object({
      胸部: z.object({ 状态: z.string().prefault('白皙挺立'), 乳头: z.string().prefault('淡粉平坦'), 敏感度: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(50) }).prefault({ 状态: '白皙挺立', 乳头: '淡粉平坦', 敏感度: 50 }),
      阴道: z.object({ 状态: z.string().prefault('粉嫩闭合'), 湿润度: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(30), 敏感度: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(50) }).prefault({ 状态: '粉嫩闭合', 湿润度: 30, 敏感度: 50 }),
      肛门: z.object({ 状态: z.string().prefault('浅粉紧致') }).prefault({ 状态: '浅粉紧致' }),
      嘴: z.object({ 状态: z.string().prefault('粉润轻抿') }).prefault({ 状态: '粉润轻抿' }),
      肌肤: z.object({ 状态: z.string().prefault('白皙干爽'), 体温: z.string().prefault('微温') }).prefault({ 状态: '白皙干爽', 体温: '微温' }),
      大腿: z.object({ 状态: z.string().prefault('白皙并拢') }).prefault({ 状态: '白皙并拢' }),
      臀部: z.object({ 状态: z.string().prefault('白皙圆润') }).prefault({ 状态: '白皙圆润' }),
    }).prefault({ 胸部: { 状态: '白皙挺立', 乳头: '淡粉平坦', 敏感度: 50 }, 阴道: { 状态: '粉嫩闭合', 湿润度: 30, 敏感度: 50 }, 肛门: { 状态: '浅粉紧致' }, 嘴: { 状态: '粉润轻抿' }, 肌肤: { 状态: '白皙干爽', 体温: '微温' }, 大腿: { 状态: '白皙并拢' }, 臀部: { 状态: '白皙圆润' } }),
    生理周期: z.object({
      月经日: z.coerce.number().transform(v => _.clamp(v, 0, 28)).prefault(1),
      周期天数: z.coerce.number().transform(v => _.clamp(v, 21, 35)).prefault(28),
      月经状态: z.enum(['经期', '卵泡期', '排卵期', '黄体期']).prefault('卵泡期'),
      经期开始日: z.coerce.number().transform(v => _.clamp(v, 0, 28)).prefault(1),
      怀孕: z.boolean().prefault(false),
      怀孕周数: z.coerce.number().transform(v => _.clamp(v, 0, 42)).prefault(0),
      避孕: z.boolean().prefault(true),
      备孕: z.boolean().prefault(false),
      排卵日: z.coerce.number().transform(v => _.clamp(v, 0, 28)).prefault(14),
    }).prefault({ 月经日: 1, 周期天数: 28, 月经状态: '卵泡期', 经期开始日: 1, 怀孕: false, 怀孕周数: 0, 避孕: true, 备孕: false, 排卵日: 14 }),
    心理状态: z.object({
      欲望度: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(20).describe('性癖标签 5 阶段调度轴（潜伏/萌芽/沉溺/失控/完全沉沦）'),
      羞耻感: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(40),
      兴奋: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(10),
      期待: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(10),
      精神状态: z.string().prefault('正常').describe('清醒/恍惚/失神/崩溃/依恋'),
    }).prefault({ 欲望度: 20, 羞耻感: 40, 兴奋: 10, 期待: 10, 精神状态: '正常' }),
    核心性癖: z.string().prefault('').describe('标签无法覆盖的性癖细节（具体表现/触发条件），随欲望度在叙事中体现'),
    心声: z.string().prefault(''),
    近期经历: z.array(z.object({
      时间: z.string().prefault('').describe('如 1991年10月·第一学期'),
      内容: z.string().prefault('').describe('她最近在做什么/经历了什么（幕后），世界推演写回，环形保留最近 5 条'),
    }).prefault({ 时间: '', 内容: '' })).prefault([]).describe('她近期的幕后行动（世界推演写回）：叙事 AI 应让她的行为遵从这些经历'),
    履历: z.array(z.object({
      时间: z.string().prefault(''),
      内容: z.string().prefault('').describe('她的重要人生经历（世界推演/剧情沉淀追加，永不删除）'),
    }).prefault({ 时间: '', 内容: '' })).prefault([]).describe('她的生平履历：历次重要事件与变化，叙事时参考'),
  }).prefault({ 身份: '', 学院: '格兰芬多', 血统: '混血', 年级: '', 性格标签: [], 性癖标签: [], 秘密: '', 口癖: '', 关系: '', 好感度: 5, 缴械值: 0, 堕落值: 0, 缴械次数: 0, 战斗次数: 0, 胜场: 0, 败场: 0, 名器: '', 名器防御: 6, 防守值上限: 44, 技能: { 名: '', 等级: 1, 经验: 0, 技能组: {} }, 能力值: { 忍耐: 5, 持久: 5, 反攻: 5 }, 特质: '', 缺陷: '', 欲望积压: 0, 压力值: 50, 是否缴械: false, 缴械日期: '', 今日已使用: false, 道具栏: {}, 恢复技能: { 名: '', 等级: 1, 经验: 0 }, 服装: {}, 身体状态: { 胸部: { 状态: '白皙挺立', 乳头: '淡粉平坦', 敏感度: 50 }, 阴道: { 状态: '粉嫩闭合', 湿润度: 30, 敏感度: 50 }, 肛门: { 状态: '浅粉紧致' }, 嘴: { 状态: '粉润轻抿' }, 肌肤: { 状态: '白皙干爽', 体温: '微温' }, 大腿: { 状态: '白皙并拢' }, 臀部: { 状态: '白皙圆润' } }, 生理周期: { 月经日: 1, 周期天数: 28, 月经状态: '卵泡期', 经期开始日: 1, 怀孕: false, 怀孕周数: 0, 避孕: true, 备孕: false, 排卵日: 14 }, 心理状态: { 欲望度: 20, 羞耻感: 40, 兴奋: 10, 期待: 10, 精神状态: '正常' }, 核心性癖: '', 心声: '', 近期经历: [], 履历: [] }).prefault({})),
}).prefault({
  时间: { 日期: '1991年9月1日', 星期: '星期一', 时段: '上午', 学年: 5, 学期: '第一学期', 学期描述: '五年级·第一学期' },
  玩家: { 学业: { 年级: 5, 学院: '格兰芬多', 血统: '混血', 各科: { 魔咒学: 82, 变形术: 75, 黑魔法防御术: 88, 魔药学: 70, 草药学: 65, 天文学: 72, 魔法史: 60 }, 学业总分: 512 }, 属性: { 体力: 80, 魔力值: 76, 魔法感知: 60 }, 魔力阶位: { 大境界: 1, 层: 1, 层进度: 0, 突破进度: 0, 心魔状态: '无', 突破记录: [] }, 状态: { 情欲: 30, 快感: 10 }, 咒语: { 昏昏倒地: { 等级: 1, 经验: 0 }, 火焰熊熊: { 等级: 1, 经验: 0 }, 摄神取念: { 等级: 1, 经验: 0 }, 统统石化: { 等级: 1, 经验: 0 }, 厉火咒: { 等级: 1, 经验: 0 }, 粉身碎骨: { 等级: 1, 经验: 0 }, 万弹齐发: { 等级: 1, 经验: 0 } }, 魔咒库: {}, 装备: { 魔杖: { 名: '冬青木魔杖', 材质: '冬青木', 杖芯: '凤凰尾羽', 品级: '普通' }, 巫师袍: { 名: '校服巫师袍', 品级: '普通' }, 饰品: {} }, 材料: {}, 财产: { 金加隆: 20, 西可: 0, 纳特: 0 }, 魔药: { 福灵剂: 0, 迷情剂: 0, 复方汤剂: 0, 欢欣剂: 1, 润滑魔油: 2, 安神药剂: 1, 突破魔药: 0 }, 战绩: { 今日胜场: 0, 今日败场: 0, 累计缴械: 0, 累计被缴械: 0 }, 生理: { 今日射精次数: 0, 射精冷却剩余: 0, 最后射精日期: '', 晨勃: true, 上次恢复体力日期: '', 上次推进日期: '' } },
  课表: { 今日场次: {}, 当前目标: '', 战斗状态: '未开始', 战斗: { 回合: 0, 主角防守值: 96, 主角防守值上限: 96, 她防守值: 44, 她防守值上限: 44, 麻痒点: 0, 主角麻痒点: 0, 她减伤修正: 0, 目标列表: [], 目标防守值: {}, 本场经验: {}, 主角BUFF: {}, 她BUFF: {} } },
  双修: { 会话状态: '未开始', 对象: '', 主导方: '我来', 当前体位: '尚未明确', 本轮动作: [], 使用物品: '不使用物品', 修为进度: 0, 情欲: 0, 快感: 0, 堕落: 0, 顺从: 0, 高潮待宣: false, 快感清零: false, 下轮高潮: false, 裁决状态: '等待触发', 可回溯: false, 历史轮: [] },
  女巫角色: {},
});

export type Schema = z.output<typeof Schema>;
