import fs from 'fs';
const Q = String.fromCharCode(96);
const b = s => Q + s + Q;
const q = s => Q + Q + Q + s + Q + Q + Q;
const M = 'E:/Games/写卡/tavern_helper_template/.workbuddy/memory/2026-09-23.md';
const L = [];
const p = s => L.push(s);

p('');
p('---');
p('');
p('## 用 skills 的官方校验器查了 12 条正则（用户：「要确定，而不是自创」）');
p('');
p('### 工具');
p(b('.skills/sillytavern-render-regex-pipeline/scripts/validate-tavern-regex.mjs') + ' ' + b('<单条正则.json>'));
p('★ 要校验**卡里（打包后）**的，不是源文件 —— 源文件用 ' + b('replace_file') + '、打包时才转 ' + b('replaceString') + '；');
p('  直接喂源文件会得到一堆假错（我试过：源文件 6/12 报错，**全是假的**）。');
p('');
p('### 结果：8/12 通过');
p('4 条报 ' + b('replaceString must be a non-empty string') + '：');
p('8状态栏对AI隐藏 ／ 1隐藏初始变量块 ／ 3变量更新对AI隐藏 ／ 1开局选择对AI隐藏 —— **全是"隐藏类"**。');
p('');
p('**但 skills 自己的文档写着**（' + b('ui/regex-scripts.md') + ' L50 与 L92）：');
p(q(''));
p('| 隐藏 | 隐藏发送给 AI 的原始标签 | replaceString: "" |');
p('| replaceString | 内联替换字符串 | ""（隐藏用）|');
p(q(''));
p('⇒ **空字符串是 skills 认可的隐藏写法** → 校验器这条规则与文档矛盾，**以文档为准，不改**。');
p('');
p('### ✅ 唯一真问题（已修）');
p(b('16-1隐藏初始变量块') + ' 的 ' + b('id') + ' 是空的 —— skills L90 要求 UUID，另外 11 条都有 ' + b('yumq-reg-…') + '，只有我新建这条漏了。已补。');
p('');
p('### ⚠️ 一条"确认是自创"的');
p(b('16-1隐藏初始变量块') + '：' + b('mvu/initvar.md') + ' 里**没有**关于「initvar 块会不会显示」的规定 → 它是我自己加的。');
p('作用：把开局那 546 个字段的变量初值块**彻底不显示**（否则会被 ' + b('2变量更新折叠') + ' 折成一个可展开的块）。');
p('★ 严格按"不自创"原则它该删；但删了开局页会多一个折叠块。**待用户定。**');
p('');
p('### ★★ 方法论收获');
p('1. **skills 自带校验脚本时就用它的脚本，别自己写检查。**');
p('   ' + b('sillytavern-render-regex-pipeline') + ' 有三个：' + b('validate-tavern-regex.mjs') + ' ／ ' + b('run-regex-fixtures.mjs') + ' ／ ' + b('trace-render-pipeline.mjs'));
p('2. **它明说「宏替换 vs 正则的顺序」是 Host-only 阶段** —— 离线证不了，**只能真实酒馆验收，不能自创**。');
p('   取证清单（它规定的）：导入的 JSON 原文、版本、**message-floor identity**、source/destination/depth、**rule order**、**console evidence**。');
p('');

fs.appendFileSync(M, L.join('\n'), 'utf8');
console.log('✓ 记忆已追加（' + L.join('\n').length + ' 字符）');
