import fs from 'fs';
const Q = String.fromCharCode(96);
const b = s => Q + s + Q;
const q = s => Q + Q + Q + s + Q + Q + Q;
const M = 'E:/Games/写卡/tavern_helper_template/.workbuddy/memory/2026-09-23.md';
const L = [];
const p = s => L.push(s);
p('');
p('---');
p('');
p('## ★★★ 面板出来了，但「时间」显示默认值 —— getVariables 的 type 写成了正则对象');
p('');
p('### 截图诊断（用户给了面板截图）');
p('对的：值全部渲染成数字不是字面量 ✅、难度正确显示「地狱」✅、成绩/理智/体力/关系等都对 ✅');
p('');
p('不对的：');
p('- **时间显示「Day 1 · 夜晚 23:00 · 回合0」**，而变量里是 ' + b('小时:7') + ' / ' + b('时段:早晨') + ' → 应是「早晨 07:00」');
p('- **12 个成员格子全是「阶段 -· Lv.」**（空的）');
p('- 今日主题空、郝佳期主线块里有个多余竖线');
p('');
p('### 真因：一个字符之差');
p(q('js'));
p('getVariables({type:/message/, message_id:id})   // ❌ type 是【正则对象】');
p('getVariables({type:"message", message_id:id})   // ✅ 必须是【字符串】');
p(q(''));
p(b('AGENTS.md') + ' 和 ' + b('@types/function/variables.d.ts') + ' 都写着：');
p('全局 ' + b("{type:'global'}") + '　角色卡 ' + b("{type:'character'}") + '　聊天 ' + b("{type:'chat'}") + '　楼层 ' + b("{type:'message', message_id}") + '。');
p('');
p('**后果**：' + b('type') + ' 不是合法值 → 返回空 → ' + b('readStat()') + ' 读不到 → ' + b('S.stat = DEFAULT_STAT') + '。');
p('于是**所有由 JS 派生的值**都显示默认值（时间/成员格子/主题…），');
p('而**用宏渲染的值是对的**（宏直接读变量，不经过 ' + b('S.stat') + '）—— 所以画面看起来"一半对一半错"。');
p('');
p('### 已修');
p('- ' + b('/message/') + ' → ' + b('"message"') + '（1 处）');
p('- ' + b('/chat/') + ' → ' + b('"chat"') + '（1 处）');
p('- 语法通过 ✓｜CDN 已推 ' + b('3b22e89') + '（HTTP 200 ✓）｜loader 指向已更新 ✓｜打包 121 条 ✓');
p('');
p('### 本轮还核对了「面板值 ↔ 变量结构」');
p('面板 353 条宏路径 **全部合法**：330 条直接命中 ' + b('initvar.yaml') + '，');
p('另 23 条也都在 ' + b('schema.ts') + ' 里有定义（' + b('群.成员详情.X.此刻想法') + '、' + b('.专属.竞技纪录') + '），只是 initvar 没给初值 →');
p('由 schema 的 ' + b('prefault') + '/' + b('catch') + ' 兜底，显示空而不是报错 ✓');
p('');
p('### ★ 教训（同一个毛病第三次了）');
p('**' + b('AGENTS.md') + ' 里写着的东西我又没照抄。**');
p(b('getVariables') + ' 的参数格式在那里白纸黑字，我凭印象写了正则对象。');
p('⇒ 用任何接口前，**先去 ' + b('@types/') + ' 或 ' + b('AGENTS.md') + ' 抄签名**，不要凭记忆写。');
p('');

fs.appendFileSync(M, L.join('\n'), 'utf8');
console.log('✓ 记忆已追加（' + L.join('\n').length + ' 字符）');
