import fs from 'fs';
const Q = String.fromCharCode(96);
const b = s => Q + s + Q;
const M = 'E:/Games/写卡/tavern_helper_template/.workbuddy/memory/2026-09-22.md';
const L = [];
const p = s => L.push(s);

p('');
p('---');
p('');
p('## ★★★ 变量更新了但面板不更新 —— 面板缺「自动重绘」（用户：「mvu变量不更新到html面板上」）');
p('');
p('### 根因：我的面板只在加载时 render 一次，之后再没重绘过');
p('同级生2 有**三套自动刷新 + 指纹防重排**，我一套都没有：');
p('');
p('| 机制 | 同级生2 的做法 |');
p('|---|---|');
p('| ① 酒馆事件 | MESSAGE_UPDATED / MESSAGE_RENDERED / MESSAGE_SWIPED / CHAT_CHANGED / GENERATION_ENDED / VARIABLES_UPDATED / VARIABLE_CHANGED → 可能重绘 |');
p('| ② MVU 事件 | ' + b('Mvu.eventOn(Mvu.events.VARIABLE_UPDATE_ENDED, () => 可能重绘(true))') + ' ← 比酒馆事件更准 |');
p('| ③ 兜底轮询 | ' + b('setInterval(可能重绘, 1500)') + '（MVU 写变量未必派发事件） |');
p('| 防重排 | ' + b('指纹取()') + ' = ' + b('JSON.stringify(stat_data)') + '，指纹变了才真重绘 |');
p('');
p('**已照抄落进 欲妈群 面板** ✓（重绘前会先 ' + b('readStat()') + ' 重新读一遍变量）');
p('');
p('### ②「变量和面板词汇不统一」的核对结果');
p('做了两次机器核对，**都没查出不一致**：');
p('1. **字段名环**：从面板抽出所有读的路径（33 个字段名），对 initvar 的 546 个字段路径 → **缺失 0 个** ✅');
p('2. **顶层环**：面板读 8 个顶层（元数据/玩家/郝佳期/假阳具/群/局面/阶段守卫/设置）＝ initvar 顶层 8 个 ✅');
p('3. **显示名**：面板写「性欲」读的是 ' + b('玩家.身体.性欲') + '、「怀疑」读 ' + b('玩家.心理.怀疑') + '、「暴露度」读 ' + b('群.成员详情.{UID}.暴露度') + ' —— **名与字段一一对应** ✅');
p('');
p('⇒ **他看到的"词汇不统一"，很可能是"面板不刷新"造成的错觉**（面板停在旧值，看起来像两套词）。');
p('   三套刷新修完，需要他再看一次；若仍有具体两处对不上，让他指出是哪两个词。');
p('');
p('### 验收');
p('面板 JS 通过｜打包 121 条｜push **b1959da**');
p('');
p('### ★ 教训');
p('**"变量变了但界面不变"永远是刷新机制的问题，不是变量的问题。**');
p('照抄能跑的卡（同级生2）时，连它的"事件绑定 + 轮询 + 指纹"整套一起抄，别只抄渲染函数。');
p('');

const log = L.join('\n');
fs.appendFileSync(M, log, 'utf8');
console.log('✓ 记忆已追加（' + log.length + ' 字符）');
