import fs from 'fs';
const Q = String.fromCharCode(96);
const b = s => Q + s + Q;
const q = s => Q + Q + Q + s + Q + Q + Q;
const M = 'E:/Games/写卡/tavern_helper_template/.workbuddy/memory/2026-09-23.md';
const L = [];
const p = s => L.push(s);

p('# 2026-09-23');
p('');
p('## ★★★ 酒馆 MCP 打通 + 面板「变量不显示」的正解落地');
p('');
p('### ① 酒馆 MCP 打通（403 → 通）');
p('症状：' + b('mcp__sillytavern__*') + ' 全部 ' + b('HTTP 403 Forbidden') + '。');
p('诊断：' + b('E:/Games/SillyTavern/config.yaml') + ' 里 ' + b('enableUserAccounts: true') + ' —— ');
p('开了用户账户后 API 需要登录 session，而 MCP 的请求没有。');
p('（' + b('basicAuthMode') + ' 和 ' + b('whitelistMode') + ' 都是 false，所以不是它们的问题。）');
p('');
p('改动（已备份 ' + b('config.yaml.bak-20260923-084140') + '）：');
p(q('yaml'));
p('enableUserAccounts: false   # 原 true');
p(q(''));
p('**重启酒馆后生效**（config 是启动时读的，热改不管用）。验证：');
p(b('st_status') + ' → ' + b('{version: 2.7.0, characters: 3, worldbooks: 13}') + ' ✅');
p('');
p('★ 注意：**这个酒馆里没有「欲妈群」卡**（3 个角色、13 本世界书都没有）——');
p('  他平时是在**另一个酒馆实例**里玩它。以后要看它的楼层，得先把卡导进这个 ST，');
p('  或在他玩的那个实例上也开 MCP。');
p('');
p('### ② 面板「变量不显示」的根因与正解');
p('**根因**：面板走 CDN（' + b("$('body').load(URL)") + '）时，**注入的内容不经过 ST 的宏替换**');
p('→ 那些 ' + b('{{format_message_variable::…}}') + ' 永远停在旧值（或字面量）→ 看起来就是"变量没显示到面板"。');
p('');
p('**正解：内联**（' + b('replace_file') + '）—— 让正则把面板**原文**注入，ST 渲染楼层时才会替换宏。');
p('');
p('已改：');
p('| 项 | 改前 | 改后 |');
p('|---|---|---|');
p('| ' + b('14-9状态栏界面.json') + ' | ' + b('replaceString') + '（524 字符 loader）| ' + b('replace_file: 正则/状态栏.html') + ' |');
p('| 18-12开局选择界面 | 已内联 | 不变 |');
p('| 卡里状态栏 | 524 字符 loader | **115207 字符，含 531 个 ST 宏，0 loader** |');
p('| ' + b('push-ui.cjs') + ' | 推 CDN + 改 loader | **停用 ①②③ 三步**，只保留打包 + 导世界书 |');
p('');
p('**要重新导卡**才生效。');
p('');
p('### ★ 教训');
p('**ST 的宏只在「内联进正则 replaceString」的位置才会被替换**；');
p('走 CDN 异步注入的内容，宏替换时机不可靠 —— 面板要显示变量，就别用 CDN。');
p('（同理：CDN 还会带来缓存问题 —— 见 09-22 的「固定 commit」那条。）');
p('');

const 内容 = L.join('\n');
fs.writeFileSync(M, 内容, 'utf8');
console.log('✓ 已写 ' + M + '（' + 内容.length + ' 字符）');
