import fs from 'fs';
const Q = String.fromCharCode(96);
const b = s => Q + s + Q;
const M = 'E:/Games/写卡/tavern_helper_template/.workbuddy/memory/2026-09-23.md';
const L = [];
const p = s => L.push(s);
p('');
p('---');
p('');
p('## ★★★ skills 有明文：宏替换 vs 正则的顺序，属于【必须真实酒馆验收】的 Host-only 阶段');
p('');
p('用户提醒「好好看看 mcp 和 skills，要确定而不是自创」—— 去读了：');
p(b('.skills/sillytavern-render-regex-pipeline/') + '（+ ' + b('references/render-stages.md') + '）');
p('');
p('### 它明写的边界');
p('**Offline stages（离线能证）**：JSON 结构、正则能否编译、enabled/placement/destination/depth、');
p('确定性 JS 替换输出、fixture 通过数、喂给 runner 的规则顺序。');
p('');
p('**Host-only stages（离线证不了，必须真实酒馆验收）**：');
p('- ★ **macro and variable substitution before or after regex execution** ← **正是我卡住的这一条**');
p('- Markdown conversion and message formatting');
p('- global / preset / character regex **merge order**');
p('- **edit、swipe、reload、chat-switch、streaming lifecycle**');
p('- extension-specific iframe / helper behavior');
p('');
p('### 它的取证要求（Disagreement protocol）');
p('> 当宿主输出与预期不符时：保留 fixture，并收集 —— 导入的 JSON 原文、装的是什么版本、');
p('> **message-floor identity**、source / destination / depth、**rule order**、**console evidence**。');
p('> **只从被验证的行为更新离线结论；绝不要为了让 fixture 通过而改 fixture。**');
p('');
p('⇒ **"宏替换在正则之前还是之后"不能靠读代码或自创来定，必须到真实酒馆里测。**');
p('   我这几轮一直在自创（内联→CDN→fetch 原文当模板），每换一种就重来一次。');
p('');
p('### 下一步该取的证据（一条就能定案）');
p('**面板上显示的是数字，还是 ' + b('{{format_message_variable::…}}') + ' 字面量？**');
p('- 显示**字面量** → ST **没**替我替换宏 → 值必须由 JS 填');
p('- 显示**数字但停住** → ST **替**我替换了（在正则之后）→ 该走内联，或让 JS 重填');
p('配合 **F12 Console** 的报错一起看（skills 要求的 console evidence）。');
p('');
p('### 我当前的修法（先留着用，但如实说明）');
p('loader 挂 ' + b('window.__YMQ_URL') + ' → 面板 ' + b('fetch') + ' 自己那份**含宏的原文**当模板 → 每次重绘重填。');
p('★ 这个做法**没有 skills 背书**，但它对上面两种情况**都能工作**，所以先跑；');
p('  等拿到实际证据，再决定要不要回到 skills 的纯正路线（内联 + 交给 ST 替换）。');
p('');

fs.appendFileSync(M, L.join('\n'), 'utf8');
console.log('✓ 记忆已追加（' + L.join('\n').length + ' 字符）');
