import fs from 'fs';
const Q = String.fromCharCode(96);
const b = s => Q + s + Q;
const q = s => Q + Q + Q + s + Q + Q + Q;
const M = 'E:/Games/写卡/tavern_helper_template/.workbuddy/memory/2026-09-23.md';
const L = [];
const p = s => L.push(s);
p('');
p('---');
p('');
p('## ★★★ 「点一个选项就消失一个」—— skills 直接否掉了我之前的做法');
p('');
p('### skills 里三条相关规范');
p('');
p('**① ' + b('sillytavern-embedded-ui') + ' · Keep state ownership explicit**');
p('状态分四类：');
p(q(''));
p('data state      持久化的游戏/配置数据');
p('draft state     可撤销、未确认的用户输入');
p('UI state        tab、展开、焦点、滚动、临时错误');
p('derived view    格式化值、计数、进度、摘要');
p(q(''));
p('> **不要把 tab、折叠、滚动位置持久化进世界书或 MVU，除非它们本来就是玩法的一部分。**');
p('> **尽量在数据刷新后保留用户控制的视图状态。**');
p('');
p('⇒ **「玩家点过哪一格」是 UI state** → 不该写进 MVU。');
p('   我原来在 ' + b('做选项()') + ' 里把 ' + b('局面.当前选项[k]') + ' **清空** —— 那是 **UI 越权改 data**。');
p('');
p('**② 同 skill · Render defensive data**');
p('> **Show malformed or unsupported data as a diagnostic state rather than silently hiding it.**');
p('⇒ 「变空就 ' + b('hidden') + '」正是规范禁止的 **silently hiding**。');
p('');
p('**③ ' + b('ui/text.md') + ' · 限制与边界**（更根本）');
p('> 纯文本版基于字符串替换，**无法执行 JavaScript 逻辑**。以下场景应改用**前端版**：');
p('> 条件显示 / 数值映射 / **进度条、动画、交互按钮** / 跨多消息的状态记忆');
p('> | 逻辑能力 | **仅宏替换** | **完整 TypeScript + Vue** |');
p('> | 适合场景 | 少量标量展示 | **复杂界面、动态交互** |');
p('');
p('⇒ **欲妈群的面板有按钮 + 进度条 + 条件显隐 + DC 映射 —— 全中"该用前端版"那一列。**');
p('   前端版 = ' + b('tavern_helper_template') + ' + Vue + pnpm + ' + b('defineMvuDataStore') + '（AGENTS.md 里推荐的 MVU store）');
p('   → 变量一变 **Vue 响应式自动重渲染**，根本不需要手写事件/轮询/指纹那一套。');
p('   ⚠️ 这是**大改**，需要用户拍板。');
p('');
p('### 本轮已改（在纯文本这条路上先按规范纠正）');
p('- 不再清空 ' + b('局面.当前选项[k]') + '（变量不动）');
p('- 改用**本地 UI 状态** ' + b('S.用过的[k]') + ' = 点的时候那格的文本');
p('- **四格常驻**；被点过的格保留显示 + 按钮 ' + b('disabled') + ' + 标「✓ 这一条这轮已经做过了」');
p('- **选项内容一变（AI 新一轮重摆）→ 自动清除已用标记 → 四格重新可点** ← 这正是用户要的');
p('- 规则侧补了「**AI 每轮必须把四格重摆满**」（D20 第五节 / 变量更新规则 / 欲妈群规则 三处）');
p('');
p('### 验收');
p('面板 JS 通过｜CDN ' + b('aca6f73') + '（HTTP 200 ✅）｜loader 已更新 ✅｜打包 121 条 ✅');
p('');
p('### ★ 教训');
p('**"UI state 该不该持久化"这件事，skills 有明文规定** —— 我凭直觉把"点过的格子清掉"写进了变量，');
p('既越权又制造了"点一下少一个"的假象。**改交互行为前先查 ' + b('sillytavern-embedded-ui') + '。**');
p('');

fs.appendFileSync(M, L.join('\n'), 'utf8');
console.log('✓ 记忆已追加（' + L.join('\n').length + ' 字符）');
