import fs from 'fs';
const Q = String.fromCharCode(96);
const b = s => Q + s + Q;
const q = s => Q + Q + Q + s + Q + Q + Q;
const M = 'E:/Games/写卡/tavern_helper_template/.workbuddy/memory/2026-09-23.md';
const L = [];
const p = s => L.push(s);
p('');
p('---');
p('');
p('## ★★★ 状态栏严格按 skills 走 CDN（用户：「状态栏肯定按照 skills 走 CDN 啊」）');
p('');
p('### 我做错的：把 91KB 面板直接内联进正则');
p('理由是"内联才能让 ST 替换宏" —— 但这**不符合 skills**，而且 ST 的 ' + b('securityOverride: true') + ' 会消毒内联的 ' + b('<script>') + '。');
p('');
p('### skills 的标准做法（' + b('ui/text.md') + ' + ' + b('ui/regex-scripts.md') + '）');
p(b('ui/text.md') + ' 明写：**含 ' + b('<body>') + ' 的前端界面** —— 文件首尾要用 3 个反引号行包裹成**独立代码块**，');
p('酒馆据此把它渲染为独立前端界面（HTML 规范不允许 ' + b('<body>') + ' 嵌套在内联消息流里）。');
p('内容里用 ' + b("$('body').load('https://testingcf.jsdelivr.net/gh/{USER}/{REPO}/...')") + ' 拉面板本体。');
p('');
p(b('regex-scripts.md') + ' 明写：替换脚本用 ' + b('replace_file') + ' 指向那个 HTML 文件。');
p('');
p('⇒ **正解 = ' + b('replace_file') + ' 指向「带围栏的 loader 文件」＋ 面板本体放 CDN**。');
p('（我之前只做了一半：要么纯 loader 没围栏、要么把全文内联。两种都不规范。）');
p('');
p('### 已改回');
p('| 文件 | 内容 |');
p('|---|---|');
p('| ' + b('正则/状态栏界面.html') + ' | **新建**：' + b(Q + Q + Q) + ' + ' + b('<body>') + ' + loader + ' + b('</body>') + ' + ' + b(Q + Q + Q) + '（479 字符）|');
p('| ' + b('14-9状态栏界面.json') + ' | ' + b('replace_file: "正则/状态栏界面.html"') + '，删 ' + b('replaceString') + ' |');
p('| ' + b('正则/状态栏.html') + ' | 面板本体（115196 字符，含 531 个 ST 宏）保留作源 |');
p('| ' + b('src/欲妈群/_cdn/') + ' | **CDN 仓库副本挪到这里**（用户要求：别放根目录，放欲妈群的文件夹里）|');
p('');
p('卡里核验：loader 491 字符 ✓ 指向 ' + b('@2ea34d2') + ' ✓ 含围栏 ✓ 世界书 121 / 正则 12 / 开场白 15 ✓');
p('');
p('### 附带修掉的（skills 那条「别和预设重复处理同一个标签」）');
p('查了预设 ' + b('梦鲸思客V4-0915.json') + '，它里面**本来就有**：');
p(b('【[🥷隐藏]对AI屏蔽MVU变量更新】') + ' ' + b('/<UpdateVariable>[\\s\\S]*?<\\/UpdateVariable>/gi') + ' M/P=false/true');
p('⇒ 卡里的 ' + b('3变量更新对AI隐藏') + ' 与它**完全相同功能** → 按 skills 改成 ' + b('disabled: true') + '（**保留留底**，不删）。');
p('其余 11 条都是本卡独有标签（' + b('group_msg') + '/' + b('contest_notify') + '/' + b('phase_up') + '/' + b('StatusPlaceHolderImpl') + '/' + b('OpeningSelectUI') + '/' + b('task_result') + '）→ 该留。');
p('');
p('### ⚠️ 还没验证的');
p('CDN 注入的内容**不经过 ST 的宏替换**，所以那 531 个宏要靠面板 JS 的兜底 ' + b('补模板()') + ' + ' + b('补宏()') + ' 自己填。');
p('（子代理写了这层兜底 + 三套重绘，理论上能工作，但**我没在真实酒馆里验过**。）');
p('若面板出现 ' + b('{{format_message_variable::…}}') + ' 字面量，说明兜底没生效，回来查 ' + b('补模板()') + '。');
p('');
p('### ★ 教训（第二次同款）');
p('**动手前先读 skills 里对应的那两份文档**（' + b('ui/text.md') + '、' + b('ui/regex-scripts.md') + '）——');
p('「前端界面要带围栏」「正则用 replace_file」「别和预设重复」这三条都白纸黑字写着，我又自己发明了一遍。');
p('');
fs.appendFileSync(M, L.join('\n'), 'utf8');
console.log('✓ 记忆已追加（' + L.join('\n').length + ' 字符）');
