import fs from 'fs';
const Q = String.fromCharCode(96);
const b = s => Q + s + Q;
const M = 'E:/Games/写卡/tavern_helper_template/.workbuddy/memory/2026-09-23.md';
const L = [];
const p = s => L.push(s);
p('');
p('---');
p('');
p('## ★★★ 选项：照抄 旮旯给木-同级生2 的做法（用户：「同级生2 也是每一轮 MVU 更新 4 个选项后自动出现在面板上」）');
p('');
p('### 同级生2 的实现（我抄的原文）');
p(Q + 'js' + Q);
p('// renderOpts：完全按变量渲染，每次重绘整块重建');
p('var opts = 局.当前选项;');
p('if (!opts || !Object.keys(opts).length) { wrap.hidden = true; return; }');
p('keys.forEach(k => { html += \'…<button data-refuse="\'+k+\'">拒绝这个</button>\'; });');
p('box.innerHTML = html;');
p('');
p('// refuse()：只写变量 + 禁用这一批按钮，绝不改「当前选项」');
p("set('局面.玩家拒绝', String(key));");
p('Array.prototype.forEach.call(…opts button, b => { b.disabled = true; });');
p(Q + Q + Q);
p('');
p('⇒ **面板从不改选项变量**；点完只禁用按钮；**AI 下一轮重摆 → 重建 → 按钮自然恢复**。');
p('   恢复靠它的三套重绘（酒馆事件 + ' + b('Mvu.eventOn(VARIABLE_UPDATE_ENDED)') + ' + ' + b('setInterval 1500') + ' + 指纹比对）。');
p('');
p('### 我改成这样（把自创的"已用标记"删掉）');
p('| 改前（我自创的） | 改后（照同级生2） |');
p('|---|---|');
p('| ' + b('S.用过的[k]') + ' 逐格记 + 「✓ 已做过」标记 span | **删掉** |');
p('| — | ' + b('S.锁批') + ' = **四格文本拼成的指纹**；点完锁这一批 |');
p('| — | ' + b('显隐()') + ' 里比对：**指纹变了（AI 重摆）→ 自动解锁** |');
p('| 四格常驻 + 已用格禁用 | 四格常驻（有内容就显示，空的才藏，等 AI 摆）|');
p('');
p('★ 效果：点一个不消失 ✓ 四格都在 ✓ 点过的那批按钮灰着 ✓ **AI 下一轮重摆后四格自动变新、恢复可点** ✓');
p('');
p('### 验收');
p(b('S.用过的') + ' 残留 0 ✓｜' + b('d-done-') + ' 残留 0 ✓｜' + b('批指纹') + ' 已加 ✓｜' + b('S.锁批') + ' 4 处 ✓｜JS 通过 ✓');
p('CDN ' + b('a450bc5') + '（HTTP 200 ✅）｜loader 已更新 ✅｜卡里围栏 2 行 ✅｜打包 121 条 ✅');
p('');
p('### ★ 教训（今天第四次同款）');
p('**「同工作区已经跑通的那张卡怎么写的」永远优先于我自己的设计。**');
p('我先是自创了「点一下清空格子」，又自创了「已用标记」，两次都被打回；');
p('同级生2 的答案一直摆在那里：**面板不改变量、点完禁用、等重摆**。');
p('');

fs.appendFileSync(M, L.join('\n'), 'utf8');
console.log('✓ 记忆已追加（' + L.join('\n').length + ' 字符）');
