import fs from 'fs';
const Q = String.fromCharCode(96);
const b = s => Q + s + Q;
const M = 'E:/Games/写卡/tavern_helper_template/.workbuddy/memory/2026-09-23.md';
const L = [];
const p = s => L.push(s);
p('');
p('---');
p('');
p('## ★★★ 面板不跟变量走的【真根因】：模板抓的是 ST 替换过宏之后的内容');
p('');
p('用户：「四个选项变量在二楼更新了，但 HTML 上的选项变量还是一楼的」');
p('');
p('### 链条（这条也解释了之前"体力/欲望不更新"）');
p(Q + 'js' + Q);
p('function 补模板(){');
p('  if(!S.模板) S.模板=root.innerHTML;                        // ← 抓的是【当前 DOM】');
p('  if(S.模板.indexOf("{{format_message_variable")<0) return;  // ← 没 {{ 就 return');
p('  root.innerHTML=S.模板; 补宏(root);                         // 恢复模板 + 按变量填');
p('}');
p(Q + Q + Q);
p('');
p('1. 面板由 CDN 注入，**ST 在渲染楼层时会先把它那 531 个宏替换掉**');
p('2. → 首次 ' + b('补模板()') + ' 抓到的 ' + b('innerHTML') + ' 是**替换后的值**（第一楼那一刻的值）');
p('3. → 之后每次重绘，' + b('S.模板') + ' 里都没有 ' + b('{{') + ' → **直接 return**');
p('4. → **值永远停在 ST 渲染那一刻**，变量再怎么更新都不动');
p('');
p('★ 上次修 ' + b('getVariables({type:/message/})') + ' 只解决了"派生值读不到变量"那一半；');
p('  **宏那半边（面板上绝大多数数字）一直是死的** —— 所以看起来"有时好有时不好"。');
p('');
p('### 修法：不信 innerHTML，直接从 CDN 取一份含宏的原文当模板');
p('| 改动 | 内容 |');
p('|---|---|');
p('| loader | 多挂一句 ' + b('window.__YMQ_URL = U') + '，面板据此 fetch 自己那份原文 |');
p('| 面板新增 ' + b('拉原文()') + ' | ' + b('fetch(URL,{cache:"no-cache"})') + ' → 剥围栏 → **校验含 ' + b('{{') + '** → 存 ' + b('S.模板') + ' + ' + b('S.模板就绪=true') + ' → 强制重绘一次 |');
p('| ' + b('补模板()') + ' | 改成**只在 ' + b('S.模板就绪') + ' 时才重填**；没到手就**别动**（免得把 ST 填好的擦掉）|');
p('');
p('### 验收');
p('拉原文 ✅｜fetch 取原文 ✅｜模板就绪判定 ✅｜init 里已调 ✅｜不再抓 innerHTML ✅｜loader 挂 URL ✅｜JS 通过 ✅');
p('CDN ' + b('cd9fc97') + ' ✅｜loader 已更新 ✅｜打包 121 条 ✅');
p('');
p('### ★ 教训');
p('**"ST 会替换宏"和"JS 自己填宏"这两条路会互相踩。**');
p('要么完全交给 ST（那就得用内联正则），要么完全交给 JS（那就得拿得到未替换的原文）。');
p('半路混用（抓 DOM 当模板）必然出这种"看着对、其实停住"的 bug。');
p('');

fs.appendFileSync(M, L.join('\n'), 'utf8');
console.log('✓ 记忆已追加（' + L.join('\n').length + ' 字符）');
