import fs from 'fs';
const Q = String.fromCharCode(96);
const b = s => Q + s + Q;
const q = s => Q + Q + Q + s + Q + Q + Q;
const M = 'E:/Games/写卡/tavern_helper_template/.workbuddy/memory/2026-09-23.md';
const L = [];
const p = s => L.push(s);
p('');
p('---');
p('');
p('## ★★★ 状态栏卡在「正在载入」的真因：围栏重复（packer 会自己加）');
p('');
p('### 截图给出的两个线索');
p('1. 面板上下各露出一行 ' + b('…') + '（= 一个**空代码块**）');
p('2. 中间 ' + b('<body>…正在载入状态栏…') + ' 被当**裸文本**渲染');
p('');
p('### 真因：' + b('pack_yumq.mjs:628') + ' —— packer 读 ' + b('replace_file') + ' 时会自己套围栏');
p(q('js'));
p("obj.replaceString = '```html\\n' + htmlContent + '\\n```\\n';");
p(q(''));
p('而我的源文件 ' + b('正则/状态栏界面.html') + ' **自己也带了围栏** → **双重包裹**：');
p(q(''));
p('```html      ← 空代码块开始');
p('```          ← 空代码块立刻结束');
p('<body>…      ← 变成裸文本（HTML 规范不允许 body 嵌在消息流里）');
p('</body>');
p('```');
p('```          ← 又一个空代码块');
p(q(''));
p('⇒ 所以状态栏**根本没被渲染成独立界面**，只剩一个转圈的占位。');
p('');
p('### 修法');
p('**源文件不带围栏**（只写 ' + b('<body>…</body>') + '），让 packer 套那对围栏。');
p('修后卡里：' + b('```html') + ' + ' + b('<body>…</body>') + ' + ' + b('```') + ' → 围栏 **2 行** ✅');
p('');
p('### ★ 和 skills 的关系（容易看错的一处）');
p(b('ui/text.md') + ' 说「含 ' + b('<body>') + ' 的界面，文件首尾要用 3 个反引号包裹」——');
p('那是给**直接用 ST 原生 ' + b('replace_file') + '** 的卡说的。');
p('**我们这条管线里 packer 已经代劳了**，所以源文件不该再带。');
p('判据：**看 packer 有没有加**，不要只看 skills 的原文。');
p('');
p('### 顺带确认的');
p('截图右下角 ' + b('11/15') + ' → swipe 11 ✓（第 11 个开局 = 地狱×场景1 ✓），说明 15 开局与难度选择那条链是通的。');
p('CDN ' + b('@2ea34d2/index.html') + ' → HTTP 200 ✓（面板本体能拉到）。');
p('');

fs.appendFileSync(M, L.join('\n'), 'utf8');
console.log('✓ 记忆已追加（' + L.join('\n').length + ' 字符）');
