// 生成 创作规划.yaml —— 严格按 skills 的类型定义推导，**不照抄 euphoria**
// 判据来源：references/requirements/entry-types.md（每类的「承载信息 / 边界说明」）
//   世界观   = 世界规则、物理法则、社会结构（"是什么"）；**不含具体角色信息**
//   扮演准则 = 叙述风格、禁止行为、语气要求（"怎么演"）；**全局约束，不是角色专属**
//   阶段指导 = 阶段化玩法/主持策略；**必须 EJS 控制，通常合并为 scope: catalog 的总指导条目**
//   时间线   = 历史事件、当前剧情进度（"事件序列"）；不是世界观
//   地理     = 区域概览 / 场景详情 / 势力
//   角色     = 核心角色人设（basic / personality / tri_faceted / other）
//   NPC      = 功能性配角；不写 personality / tri_faceted
//   事件     = 单次触发的内容；不是时间线
//   MVU      = 变量系统
// 可重复运行（覆盖）。
const fs = require('fs');
const P = '创作规划.yaml';

const 女角 = ['鸣泽唯','水野友美','筱原泉','南川洋子','加藤美纪','舞岛可怜','杉本樱子','都筑梢',
  '野野村美里','安田爱美','田中美沙','片桐美铃','鸣泽美佐子','永岛佐知子','永岛久美子'];
const 男配 = ['川尻彰','长冈芳树','西御寺有友','天道新干线'];
const 区域 = ['住宅区','八十八学园','商业区','车站与娱乐','郊外','如月町','温泉乡','医院'];
// 引擎层：按 skills 判据分两类 —— 世界规则 → 世界观；AI 行为 → 扮演准则
const 引擎_世界观 = ['四态循环','反抗与判定','兴奋度机制','出招','交互循环','剧情推进','边界情况','离线行动'];
const 引擎_扮演准则 = ['加载纪律','判定引擎','推演链','叙述准则','感知禁令','玩家的输入'];
const 人设 = ['温砚','丰娆','舒晏','唐响','沈眠','莫漾','纪清'];
const PART = ['basic','personality','tri_faceted','other'];
const PART名 = { basic:'基础信息', personality:'性格调色盘', tri_faceted:'三面性', other:'NSFW反差与剧情线' };
const 昵称 = { 鸣泽唯:['小唯'], 水野友美:['友美'], 筱原泉:['泉'], 南川洋子:['洋子'], 加藤美纪:['美纪'],
  舞岛可怜:['可怜'], 杉本樱子:['樱子'], 都筑梢:['梢'], 野野村美里:['美里'], 安田爱美:['爱美'],
  田中美沙:['美沙'], 片桐美铃:['片桐老师','美铃'], 鸣泽美佐子:['美佐子'], 永岛佐知子:['佐知子'],
  永岛久美子:['久美子'] };
const 职务 = { 川尻彰:['好朋友'], 长冈芳树:['问题儿童'], 西御寺有友:['财阀独生子'], 天道新干线:['体育老师'] };

const L = [];
const P2 = s => `  ${s}`;
L.push(
'# 创作规划.yaml — 旮旯给木 · 同级生2（底座 nanpa2）',
'#',
'# 本文是**项目级事实来源**（skills 规划同步原则）：任何修改先改本文，再改条目内容。',
'# 组织轴 = **时间轴**（design-spec §一：主题「时间的不可逆 / 被替你做决定的十七天」）。',
'# entries 数组顺序 = 默认创作顺序。',
'#',
'# ═══ 类型判定表（逐条按 skills 推导，不照抄任何已有卡）═══',
'# skills 的九种类型只有三个落点，先把它们分清楚：',
'#   ┌ AI 需要知道的 → 世界书条目（本文 entries）',
'#   ├ 代码需要知道的 → 工程文件（本文 engine_contracts，**不进 prompt = 0 token**）',
'#   └ 玩家需要看到的 → MVU 变量 + 界面（不在本文）',
'#',
'# | 内容 | skills 类型 | 判据（entry-types.md 原文） |',
'# |---|---|---|',
'# | 四态循环 / 反抗与判定 / 兴奋度机制 / 出招 / 交互循环 / 剧情推进 / 边界情况 / 离线行动 | 世界观 | 世界规则，**不含具体角色信息** |',
'# | 加载纪律 / 判定引擎 / 推演链 / 叙述准则 / 感知禁令 / 玩家的输入 | 扮演准则 | 都是「怎么演」：元规则 / 采信判定 / 推理方法 / 叙述风格 / 禁止行为 / 玩家输入归属 |',
'# | 八十八町·世界规则 | 世界观 | 时间制 / 只能选一个 / D0 / 地图三功能 = 世界怎么运转 |',
'# | 关系封闭 | 世界观 | 封闭之后世界怎么运转（矩阵本身是契约，**不进**） |',
'# | 阶段指导（含熟练度五档） | 阶段指导 | 「不同阶段的目标·叙事重点·互动方式·推进边界」+ **必须 EJS** —— 熟练度五档正是这个 |',
'# | 时间轴索引 / 人物出现索引 / 第01~17天 | 时间线 | history = 骨架与索引；plot = 当前剧情进度（17 天） |',
'# | 地理速览 + 8 region | 地理 | 区域概览 / 场景详情；**不使用 faction**（本作无势力对抗） |',
'# | 主角 / 15 女角 ×4 part / 她_×7 / 角色速览 | 角色 | 核心角色人设；part = basic / personality / tri_faceted / other |',
'# | 4 男配 | NPC | 功能性配角，**不写 personality / tri_faceted** |',
'# | 终局 | 事件 | 单次触发的内容（结局判定） |',
'# | 变量列表 / 更新规则 / 输出格式 / initvar | MVU | 变量系统 |',
'#',
'# ⚠️ 三处**刻意不同于 euphoria** —— 因为 skills 是这么要求的，不是因为 euphoria 是错的：',
'#   ① **主角 → 角色/basic**（euphoria 放 世界观/region）—— 世界观的边界写明「不含具体角色信息」',
'#   ② **熟练度阶段 → 并入 阶段指导**（euphoria 放 角色/other）—— 阶段指导的定义就是它，且规范要求 EJS 段落控制',
'#   ③ **7 套「她」→ 同 group + use_priority**（euphoria 让它们各自独立）',
'#      —— configuration.md:153 原文：`use_priority` 的用途就是「**互斥设定变体**」，组内只注入权重最高的一条',
'#',
'# ═══ 加载策略（token）—— 省的 token 从哪来 ═══',
'# ★ 17 天的 plot 条目**全部带 @@if**，依据 configuration.md:49「EJS 条目在同 part 最多计为 1」：',
'#   → 17 条只计 1 条，**常驻成本 = 1 条**；而每条自己的 @@if 只让当天那一段渲染。',
'#   好处：单条不超 5,000 字符上限，且可以一天一文件地写（可维护）。',
'# ★ 索引类（角色速览 / 地理速览）走 `scope: catalog` → 始终 constant 且不参与同 part 计数。',
'# ★ 契约类（互斥矩阵 / 目的清单 / 偏好系数）→ `engine_contracts`，**0 token**（AI 只需知道结果）。',
'# ★ 7 套「她」→ 同 group + use_priority → 7 条只注入 1 条。',
'',
'project:',
P2('name: 旮旯给木-同级生2'),
P2('worldbookName: 旮旯给木-同级生2'),
P2('form: charactercard'),
P2('mvu: true'),
P2('ui_mode: frontend        # 状态栏含拒绝按钮与 LCG 判定 → 需前端版（交 tavern-ui）'),
'',
'world:',
P2('overview: 八十八町，一个普通的日本小镇，冬天。现实世界，无任何超自然元素。全部角色为成年人。'),
P2('          玩家扮演的主角 18 岁，母亲早逝、父亲是常年在外的考古学家，寄住在鸣泽家十年。'),
P2('          唯一的非现实元素承袭引擎：他能通过摄像头看见「屏幕外的她」。'),
P2('regions:'),
...区域.map(r => P2(`  - name: ${r}`)),
P2('factions: []              # 同级生2 无势力对抗 → 不使用 faction part'),
'',
'characters:',
P2('# 主角：skills 判为「角色」（核心角色人设）—— 世界观边界写明「不含具体角色信息」'),
P2('- name: 主角'),
P2('  basic:'),
P2('    identity: 见 底座_nanpa2/主角设定.txt'),
P2('  appearance: []'),
P2('  tri_faceted: false'),
...女角.flatMap(n => [
  P2(`- name: ${n}`),
  P2('  basic:'),
  P2('    identity: 见 底座_nanpa2/女角设定.md'),
  P2('  appearance: []          # 五官权威版本在 底座_nanpa2/女角设定-外貌与NSFW.md'),
  P2('  personality:'),
  P2('    base: 见 底座_nanpa2/女角设定-补完.md（基调权威版本）'),
  P2('  tri_faceted: true'),
]),
...男配.flatMap(n => [P2(`- name: ${n}`), P2('  type: NPC'), P2(`  function: ${职务[n][0]}`)]),
P2('# 7 套「屏幕外的她」＝ 同一角色的互斥设定变体（见 entries 里的 group.use_priority）'),
...人设.map(n => P2(`- name: 她_${n}`)),
'',
'style:',
P2('perspective: 第三人称'),
P2('tone: 日常白描，不加滤镜'),
P2('mood: 日常底下的窒息感（design-spec §一 情感落点）'),
P2('reference: 无'),
'',
'# ═══════════════════════════════════════════════════════════',
'# entries —— 数组顺序即创作顺序',
'# ═══════════════════════════════════════════════════════════',
'entries:',
'  # ── 0 · 引擎层：世界规则（世界怎么运转）──',
...引擎_世界观.map(n => `  - { name: ${n}, type: 世界观, path: 世界书/世界观/引擎/${n}.yaml }`),
'  # ── 0 · 引擎层：AI 行为约束（怎么演）──',
'  - { name: 加载纪律, type: 扮演准则, path: 世界书/扮演准则/加载纪律.yaml, order: 1 }',
'  - { name: CoT注入, type: 扮演准则, path: 世界书/扮演准则/CoT注入.yaml }',
  '  - { name: 判定引擎, type: 扮演准则, path: 世界书/扮演准则/判定引擎.yaml }',
...引擎_扮演准则.slice(2).map(c => `  - { name: ${c}, type: 扮演准则, path: 世界书/扮演准则/${c}.yaml }`),
'  # ── 0 · 引擎层：阶段化主持（catalog 常驻 + EJS 段落控制）──',
'  - name: 阶段指导',
'    type: 阶段指导',
'    scope: catalog',
'    path: 世界书/阶段指导/阶段指导.yaml',
'    purpose: 四态 + 情绪 + 熟练度五档（新手/上手/沉浸/狂热/收官），每档写她的手段、给 <user> 的空间、痕迹扫描',
'    note: ★ 熟练度五档是「阶段化玩法」→ skills 判为阶段指导并**并入本条**，不单独立条',
'  # ── 1 · 底座·世界规则（不写角色信息）──',
'  - name: 八十八町',
'    type: 世界观',
'    path: 世界书/世界观/底座_nanpa2/八十八町.yaml',
'    purpose: 时间制（17 天 / 5 时段 / 见一个人消耗时间）、只能选一个、D0 指令系统、地图三功能',
'  - name: 关系封闭',
'    type: 世界观',
'    path: 世界书/世界观/底座_nanpa2/关系封闭.yaml',
'    purpose: 封闭之后世界怎么运转（哪条线关掉、哪些事件不再出现）。互斥矩阵本身是契约，不进本条',
'  # ── 2 · 时间轴层（★ 主题轴：17 天 / 一天一关 / 关内 5 时段）──',
'  - name: 时间轴索引',
'    type: 时间线',
'    part: history',
'    path: 世界书/时间线/时间轴索引.yaml',
'    purpose: 常驻索引。17 天骨架 + 5 时段 + 公共规则 + 每日锚点清单（当天的详情不在此条）',
'    note: 原「关卡序列」并进本条 —— 一个条目只承载一类信息，反过来说也不该两个条目承载一类',
'  - name: 人物出现索引',
'    type: 时间线',
'    part: history',
'    path: 世界书/时间线/人物出现索引.yaml',
'    purpose: (日期, 时段, 地点) → 在场名单，供引擎查询',
...Array.from({length:17},(_,i)=>{
  const d=i+1, dd=String(d).padStart(2,'0');
  const date = d===1?'12-22':`01-${String(d-5).padStart(2,'0')}`;
  return [`  - name: 第${dd}天`,'    type: 时间线','    part: plot',
    `    path: 世界书/时间线/plot/第${dd}天.yaml`,
    `    purpose: ${date} 的事件锚点与在场名单（EJS 按当前天数渲染）`];
}).flat(),
'  # ── 3 · 地理层（速览常驻当索引，region 按当前地点按需）──',
'  - name: 地理速览',
'    type: 地理',
'    part: region',
'    scope: catalog',
'    path: 世界书/地理/地理速览.yaml',
'    purpose: 索引条目，始终 constant 且不参与同 part 计数',
...区域.map(r => `  - { name: ${r}, type: 地理, part: region, path: 世界书/地理/${r}.yaml, keywords: [${r}] }`),
'  # ── 4 · 角色层（★ 一角色 × 4 条目：part 独立成条目，skills 的分 part 阈值才生效）──',
'  - { name: 角色速览, type: 角色, part: other, scope: catalog, path: 世界书/角色/速览.yaml }',
'  - name: 主角',
'    type: 角色',
'    part: basic',
'    path: 世界书/角色/主角/基础信息.yaml',
'    keywords: [主角]',
'  # 7 套「她」＝ 互斥设定变体：同 group + use_priority（组内只注入权重最高的一条）',
'  # skills 原文（configuration.md:153）：use_priority「用于互斥设定变体」',
...人设.flatMap(n => [
  `  - name: 她_${n}`,
  '    type: 角色',
  '    part: other',
  `    path: 世界书/角色/屏幕外的她/${n}.yaml`,
  `    keywords: [${n}]`,
  '    note: 她要什么（goal_units 的人设映射）写在本条 —— 「她想要什么」是角色的一部分，不是世界观',
]),
...女角.flatMap(n => PART.flatMap(pt => [
  `  - name: ${n}_${PART名[pt]}`,
  '    type: 角色',
  `    part: ${pt}`,
  `    path: 世界书/角色/底座_nanpa2/${n}/${PART名[pt]}.yaml`,
  `    keywords: [${[n, ...(昵称[n]||[])].join(', ')}]`,
])),
'  # ── 5 · NPC 层（不写 personality / tri_faceted）──',
...男配.flatMap(n => [
  `  - name: ${n}`,
  '    type: NPC',
  `    path: 世界书/NPC/${n}.yaml`,
  `    keywords: [${[n, ...(职务[n]||[])].join(', ')}]`,
]),
'  # ── 6 · MVU 与事件 ──',
'  - { name: "[InitVar]请勿打开", type: MVU, part: initvar, path: 世界书/变量/initvar.yaml }',
'  - { name: 变量列表, type: MVU, part: variable_list, path: 世界书/变量/变量列表.yaml }',
'  - { name: 变量更新规则, type: MVU, part: update_rules, path: 世界书/变量/变量更新规则.yaml }',
'  - { name: "[mvu_update]变量输出格式", type: MVU, part: output_format, path: 世界书/变量/变量输出格式.txt }',
'  - name: 终局',
'    type: 事件',
'    path: 世界书/事件/终局.yaml',
'    purpose: 1-07 深夜的结局判定（单次触发 → skills 判为「事件」，不是时间线）',
'',
'# ═══════════════════════════════════════════════════════════',
'# engine_contracts —— 代码需要知道的（**不进世界书，0 token**）',
'# skills 判据：契约与数值表属于机制层，落点是工程文件；AI 只需要知道结果，不需要知道规则',
'# ═══════════════════════════════════════════════════════════',
'engine_contracts:',
P2('- file: 底座_nanpa2/状态表.yaml'),
P2('  what: T2 状态表（221 状态，每个填「意义」）+ ★ 15×15 互斥矩阵（逐格照搬 + 49 对冲突）'),
P2('- file: 底座_nanpa2/initvar.yaml'),
P2('  what: 变量初始值'),
P2('- file: 底座_nanpa2/目的清单.yaml'),
P2('  what: goal_units 数值契约（88 张 CG + 7 套人设的单元映射）—— 「她要什么」的**条目版**在 她_XX，本文是**数值版**'),
P2('- file: 底座_nanpa2/偏好系数表.yaml（待写）'),
P2('  what: 出招时各女角的偏好权重 —— 引擎算给「她」看，AI 不需要'),
P2('- file: 底座_nanpa2/地理速览.yaml'),
P2('  what: T1 地图机制数据（距离 / 开放时段 / 在场名单）'),
P2('- file: 机制/判定引擎.txt'),
P2('  what: E3 判定引擎实现（LCG + 判定链），不含任何世界观/角色/地点名'),
P2('- file: Token 预算与加载策略.md'),
P2('  what: token 规范与八条手段、定稿转换清单'),
P2('- file: budget.json（待建）'),
P2('  what: 项目级预算（覆盖校验器默认值）'),
P2('- file: schema.ts（待建）'),
P2('  what: MVU 变量类型定义（由 状态表.yaml 派生）'),
'',
'mvu:',
P2('structure: |'),
'    顶层结构（详见 底座_nanpa2/状态表.yaml，T2 契约，221 个状态）：',
'    ├── 世界',
'    │   ├── 日期 / 天数 / 时段 / 时段进度 / 章节',
'    │   ├── 当前地点 / 当前女角 / 场景模式',
'    │   ├── 天气 / 只能选一个 / 互斥状态',
'    │   └── 底座（= nanpa2）',
'    ├── 主角',
'    │   ├── 身体状态 / 心情',
'    │   ├── 说话 / 做事 / 懂东西（3 维明牌）',
'    │   └── 拒绝 / 判定结果（引擎写入）',
'    ├── 女角 ×15',
'    │   └── 关系阶段 / 好感度 / 心动值 / 信任度 / 嫉妒值',
'    ├── 经济',
'    ├── 过程（世界的裂缝 / 她用过的手段）',
'    └── 剧情（日记 / 樱子线 / 美纪线 / 互斥触发 / 死结局标识）',
P2('variables: []               # 待细化：以 底座_nanpa2/状态表.yaml 为准'),
'',
'ejs:',
P2('entries:'),
'    - name: 八十八町',
'      complexity: 条目显隐',
"      condition: \"getvar('stat_data.世界.底座', { defaults: '' }) === 'nanpa2'\"",
...Array.from({length:17},(_,i)=>{
  const dd=String(i+1).padStart(2,'0');
  return [`    - name: 第${dd}天`,'      complexity: 条目显隐',
    `      condition: "getvar('stat_data.世界.天数', { defaults: 0 }) === ${i+1}"`];
}).flat(),
...区域.flatMap(r => [
  `    - name: ${r}`,
  '      complexity: 条目显隐',
  `      condition: "getvar('stat_data.世界.当前地点', { defaults: '' }).includes('${r}')"`,
]),
'    - name: 阶段指导',
'      complexity: 段落控制',
'      note: 按熟练度阶段（1-5）渲染段落，每档只渲染它自己那一节',
...人设.flatMap(n => [
  `    - name: 她_${n}`,
  '      complexity: 条目显隐',
  '      group: { labels: [屏幕外的她], use_priority: true, weight: 100 }',
  `      condition: "getvar('stat_data.她.人设', { defaults: '' }) === '${n}'"`,
]),
'    # 15 女角条目：全部套 @@if 门控（EJS 条目在同 part 最多计为 1，避免被阈值推成常驻）',
'    # 角色速览 / 地理速览：scope=catalog，始终 constant 且不参与计数（索引条目本就该常驻）',
'',
'first_messages:',
'  - format: 说明式                 # 0.txt：告知这是什么卡、状态栏怎么看、7 套「她」在哪启动',
'    output_path: 开场白/0.txt',
'  - format: 表单式                 # 1.txt：开局菜单，<OpeningPlaceHolder/> 由界面替换为 7+1 个选项',
'    output_path: 开场白/1.txt',
...Array.from({length:7},(_,i)=>{
  const n=i+2;
  return [`  - format: 叙事式                 # ${n}.txt：${人设[i]} · 12-22 早上，自宅，寒假第一天`,
    '    word_count: 500~700', `    output_path: 开场白/${n}.txt`,
    `    initvar_override: 开场白/initvar/${n}.yaml`];
}).flat(),
);

fs.writeFileSync(P, L.join('\n') + '\n');
console.log('✅ 已生成 创作规划.yaml');
