export const Schema = z.object({
  时间: z.object({
    日期: z.string().prefault('2026年9月1日'),
    星期: z.string().prefault('星期一'),
    时段: z.enum(['上午', '下午场', '晚场', '深夜']).prefault('上午'),
  }).prefault({ 日期: '2026年9月1日', 星期: '星期一', 时段: '上午' }),
  玩家: z.object({
    学业总分: z.preprocess(v => Array.isArray(v) ? Number(v[0]) : v, z.coerce.number().transform(v => _.clamp(v, 0, 750))).prefault(420),
    各科: z.object({
      语文: z.coerce.number().transform(v => _.clamp(v, 0, 150)).prefault(100),
      数学: z.coerce.number().transform(v => _.clamp(v, 0, 150)).prefault(85),
      英语: z.coerce.number().transform(v => _.clamp(v, 0, 150)).prefault(95),
      物理: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(70),
      化学: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(80),
      生物: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(90),
    }).prefault({ 语文: 100, 数学: 85, 英语: 95, 物理: 70, 化学: 80, 生物: 90 }),
    技能: z.object({
      螺旋: z.object({ 等级: z.coerce.number().transform(v => _.clamp(v, 1, 20)).prefault(1), 经验: z.coerce.number().transform(v => _.clamp(v, 0, 9999)).prefault(0) }).prefault({ 等级: 1, 经验: 0 }),
      颗粒: z.object({ 等级: z.coerce.number().transform(v => _.clamp(v, 1, 20)).prefault(1), 经验: z.coerce.number().transform(v => _.clamp(v, 0, 9999)).prefault(0) }).prefault({ 等级: 1, 经验: 0 }),
      敏感度加倍: z.object({ 等级: z.coerce.number().transform(v => _.clamp(v, 1, 20)).prefault(1), 经验: z.coerce.number().transform(v => _.clamp(v, 0, 9999)).prefault(0) }).prefault({ 等级: 1, 经验: 0 }),
      硬度翻倍: z.object({ 等级: z.coerce.number().transform(v => _.clamp(v, 1, 20)).prefault(1), 经验: z.coerce.number().transform(v => _.clamp(v, 0, 9999)).prefault(0) }).prefault({ 等级: 1, 经验: 0 }),
      热量翻倍: z.object({ 等级: z.coerce.number().transform(v => _.clamp(v, 1, 20)).prefault(1), 经验: z.coerce.number().transform(v => _.clamp(v, 0, 9999)).prefault(0) }).prefault({ 等级: 1, 经验: 0 }),
      次数翻倍: z.object({ 等级: z.coerce.number().transform(v => _.clamp(v, 1, 20)).prefault(1), 经验: z.coerce.number().transform(v => _.clamp(v, 0, 9999)).prefault(0) }).prefault({ 等级: 1, 经验: 0 }),
      频率翻倍: z.object({ 等级: z.coerce.number().transform(v => _.clamp(v, 1, 20)).prefault(1), 经验: z.coerce.number().transform(v => _.clamp(v, 0, 9999)).prefault(0) }).prefault({ 等级: 1, 经验: 0 }),
    }).prefault({ 螺旋: { 等级: 1, 经验: 0 }, 颗粒: { 等级: 1, 经验: 0 }, 敏感度加倍: { 等级: 1, 经验: 0 }, 硬度翻倍: { 等级: 1, 经验: 0 }, 热量翻倍: { 等级: 1, 经验: 0 }, 次数翻倍: { 等级: 1, 经验: 0 }, 频率翻倍: { 等级: 1, 经验: 0 } }),
    体力: z.preprocess(v => Array.isArray(v) ? Number(v[0]) : v, z.coerce.number().transform(v => _.clamp(v, 0, 100))).prefault(80),
    性欲: z.preprocess(v => Array.isArray(v) ? Number(v[0]) : v, z.coerce.number().transform(v => _.clamp(v, 0, 100))).prefault(30),
    勃起度: z.preprocess(v => Array.isArray(v) ? Number(v[0]) : v, z.coerce.number().transform(v => _.clamp(v, 0, 100))).prefault(10),
    今日胜场: z.coerce.number().transform(v => _.clamp(v, 0, 99)).prefault(0),
    今日败场: z.coerce.number().transform(v => _.clamp(v, 0, 99)).prefault(0),
    累计缴械: z.coerce.number().transform(v => _.clamp(v, 0, 999)).prefault(0),
    累计被缴械: z.coerce.number().transform(v => _.clamp(v, 0, 999)).prefault(0),
    道具栏: z.object({
      印度神油: z.coerce.number().transform(v => _.clamp(v, 0, 99)).prefault(3),
      伟哥: z.coerce.number().transform(v => _.clamp(v, 0, 99)).prefault(2),
      辣椒油: z.coerce.number().transform(v => _.clamp(v, 0, 99)).prefault(1),
      六神花露水: z.coerce.number().transform(v => _.clamp(v, 0, 99)).prefault(1),
      清凉油: z.coerce.number().transform(v => _.clamp(v, 0, 99)).prefault(0),
      润滑液: z.coerce.number().transform(v => _.clamp(v, 0, 99)).prefault(2),
    }).prefault({ 印度神油: 3, 伟哥: 2, 辣椒油: 1, 六神花露水: 1, 清凉油: 0, 润滑液: 2 }),
    恢复技能: z.object({
      提肛: z.object({ 等级: z.coerce.number().transform(v => _.clamp(v, 1, 20)).prefault(1), 经验: z.coerce.number().transform(v => _.clamp(v, 0, 9999)).prefault(0) }).prefault({ 等级: 1, 经验: 0 }),
      思维分散: z.object({ 等级: z.coerce.number().transform(v => _.clamp(v, 1, 20)).prefault(1), 经验: z.coerce.number().transform(v => _.clamp(v, 0, 9999)).prefault(0) }).prefault({ 等级: 1, 经验: 0 }),
    }).prefault({ 提肛: { 等级: 1, 经验: 0 }, 思维分散: { 等级: 1, 经验: 0 } }),
    生理: z.object({
      今日射精次数: z.coerce.number().transform(v => _.clamp(v, 0, 99)).prefault(0),
      射精冷却剩余: z.coerce.number().transform(v => _.clamp(v, 0, 24)).prefault(0),
      最后射精日期: z.string().prefault(''),
      晨勃: z.boolean().prefault(true),
      上次恢复体力日期: z.string().prefault(''),
      上次推进日期: z.string().prefault(''),
    }).prefault({ 今日射精次数: 0, 射精冷却剩余: 0, 最后射精日期: '', 晨勃: true, 上次恢复体力日期: '', 上次推进日期: '' }),
    副API配置: z.looseObject({}).optional().describe('副API描写配置(浏览器localStorage兜底,可选)'),
  }).prefault({ 学业总分: 420, 各科: { 语文: 100, 数学: 85, 英语: 95, 物理: 70, 化学: 80, 生物: 90 }, 技能: { 螺旋: { 等级: 1, 经验: 0 }, 颗粒: { 等级: 1, 经验: 0 }, 敏感度加倍: { 等级: 1, 经验: 0 }, 硬度翻倍: { 等级: 1, 经验: 0 }, 热量翻倍: { 等级: 1, 经验: 0 }, 次数翻倍: { 等级: 1, 经验: 0 }, 频率翻倍: { 等级: 1, 经验: 0 } }, 体力: 80, 性欲: 30, 勃起度: 10, 今日胜场: 0, 今日败场: 0, 累计缴械: 0, 累计被缴械: 0, 道具栏: { 印度神油: 3, 伟哥: 2, 辣椒油: 1, 六神花露水: 1, 清凉油: 0, 润滑液: 2 }, 恢复技能: { 提肛: { 等级: 1, 经验: 0 }, 思维分散: { 等级: 1, 经验: 0 } }, 生理: { 今日射精次数: 0, 射精冷却剩余: 0, 最后射精日期: '', 晨勃: true, 上次恢复体力日期: '', 上次推进日期: '' } }),
  排班: z.object({
    今日场次: z.record(z.string().describe('时段'), z.object({
      参与者: z.string().prefault(''),
      结果: z.string().prefault('未开战'),
      是否参战: z.boolean().prefault(false),
    }).prefault({ 参与者: '', 结果: '未开战', 是否参战: false })).prefault({}),
    当前战斗目标: z.string().prefault(''),
    战斗状态: z.enum(['未开始', '进行中', '已结算']).prefault('未开始'),
    战斗: z.object({
      回合: z.coerce.number().transform(v => _.clamp(v, 0, 99)).prefault(0),
      主角防守值: z.coerce.number().transform(v => _.clamp(v, 0, 200)).prefault(96),
      主角防守值上限: z.coerce.number().transform(v => _.clamp(v, 0, 200)).prefault(96),
      她防守值: z.coerce.number().transform(v => _.clamp(v, 0, 200)).prefault(44),
      她防守值上限: z.coerce.number().transform(v => _.clamp(v, 0, 200)).prefault(44),
      麻痒点: z.coerce.number().transform(v => _.clamp(v, 0, 99)).prefault(0),
      主角麻痒点: z.coerce.number().transform(v => _.clamp(v, 0, 99)).prefault(0),
      她减伤修正: z.coerce.number().transform(v => _.clamp(v, -20, 20)).prefault(0),
      目标列表: z.array(z.string()).prefault([]).describe('多人战斗参与者姓名数组（当前战斗目标=多人时使用）'),
      目标防守值: z.record(z.string(), z.coerce.number()).prefault({}).describe('多人战斗各参与者当前防守值'),
      本场经验: z.record(z.string(), z.coerce.number()).prefault({}),
      主角BUFF: z.record(z.string().describe('BUFF名'), z.object({
        剩余回合: z.coerce.number().transform(v => _.clamp(v, 0, 10)).prefault(0),
        效果值: z.coerce.number().transform(v => _.clamp(v, -20, 20)).prefault(0),
      }).prefault({ 剩余回合: 0, 效果值: 0 })).prefault({}),
      她BUFF: z.record(z.string().describe('BUFF名'), z.object({
        剩余回合: z.coerce.number().transform(v => _.clamp(v, 0, 10)).prefault(0),
        效果值: z.coerce.number().transform(v => _.clamp(v, -20, 20)).prefault(0),
      }).prefault({ 剩余回合: 0, 效果值: 0 })).prefault({}),
    }).prefault({ 回合: 0, 主角防守值: 96, 主角防守值上限: 96, 她防守值: 44, 她防守值上限: 44, 麻痒点: 0, 主角麻痒点: 0, 她减伤修正: 0, 目标列表: [], 目标防守值: {}, 本场经验: {}, 主角BUFF: {}, 她BUFF: {} }),
  }).prefault({ 今日场次: {}, 当前战斗目标: '', 战斗状态: '未开始', 战斗: { 回合: 0, 主角防守值: 96, 主角防守值上限: 96, 她防守值: 44, 她防守值上限: 44, 麻痒点: 0, 主角麻痒点: 0, 她减伤修正: 0, 本场经验: {}, 主角BUFF: {}, 她BUFF: {} } }),
  女性角色: z.record(z.string().describe('角色名'), z.object({
    身份: z.string().prefault(''),
    省份: z.string().prefault(''),
    方言: z.string().prefault(''),
    关系: z.string().prefault(''),
    好感度: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(3).describe('她对<user>的社交好感（0~100，独立于缴械值）：分档决定日常社交可做/不可做；与假阴茎完全解耦——好感度再高也不揭晓假阴茎真相，唯一解锁=缴械值100俘虏'),
    缴械值: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(0),
    缴械次数: z.coerce.number().transform(v => _.clamp(v, 0, 999)).prefault(0),
    战斗次数: z.coerce.number().transform(v => _.clamp(v, 0, 999)).prefault(0),
    胜场: z.coerce.number().transform(v => _.clamp(v, 0, 999)).prefault(0),
    败场: z.coerce.number().transform(v => _.clamp(v, 0, 999)).prefault(0),
    名器: z.string().prefault(''),
    名器防御: z.coerce.number().transform(v => _.clamp(v, 0, 10)).prefault(6),
    防守值上限: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(44),
    技能: z.object({
      名: z.string().prefault(''),
      等级: z.coerce.number().transform(v => _.clamp(v, 1, 20)).prefault(1),
      经验: z.coerce.number().transform(v => _.clamp(v, 0, 9999)).prefault(0),
      技能组: z.record(z.string().describe('辅技能名'), z.object({
        等级: z.coerce.number().transform(v => _.clamp(v, 1, 20)).prefault(1),
        经验: z.coerce.number().transform(v => _.clamp(v, 0, 9999)).prefault(0),
      }).prefault({ 等级: 1, 经验: 0 })).prefault({}),
    }).prefault({ 名: '', 等级: 1, 经验: 0, 技能组: {} }),
    能力值: z.object({
      忍耐: z.coerce.number().transform(v => _.clamp(v, 1, 10)).prefault(5),
      持久: z.coerce.number().transform(v => _.clamp(v, 1, 10)).prefault(5),
      反攻: z.coerce.number().transform(v => _.clamp(v, 1, 10)).prefault(5),
    }).prefault({ 忍耐: 5, 持久: 5, 反攻: 5 }),
    特质: z.string().prefault(''),
    缺陷: z.string().prefault(''),
    欲望积压: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(0),
    压力值: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(50).describe('她自己的生活压力（0~100，独立运转）：学生=模考/排名，老师=教学指标，陪读妈妈=生计孤独；分档驱动欲望积压自然增长与使用假阴茎意愿'),
    是否俘虏: z.boolean().prefault(false),
    俘虏日期: z.string().prefault(''),
    今日已使用: z.boolean().prefault(false),
    道具栏: z.record(z.string().describe('道具名'), z.coerce.number().transform(v => _.clamp(v, 0, 99)).prefault(0)).prefault({}),
    恢复技能: z.object({
      名: z.string().prefault(''),
      等级: z.coerce.number().transform(v => _.clamp(v, 1, 20)).prefault(1),
      经验: z.coerce.number().transform(v => _.clamp(v, 0, 9999)).prefault(0),
    }).prefault({ 名: '', 等级: 1, 经验: 0 }),
    服装: z.record(z.string().describe('部位'), z.string().prefault('')).prefault({}),
    身体状态: z.object({
      胸部: z.object({ 状态: z.string().prefault('白皙挺立').describe('胸部状态词（随刺激阶段）：白皙挺立→粉晕微胀→胀立颤巍→酸软泛红→红肿敏感，写具体视觉词勿写"正常"'), 乳头: z.string().prefault('淡粉平坦').describe('乳头词：淡粉平坦→粉嫩微立→嫣红挺立→硬挺湿亮'), 敏感度: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(50) }).prefault({ 状态: '白皙挺立', 乳头: '淡粉平坦', 敏感度: 50 }),
      阴道: z.object({ 状态: z.string().prefault('粉嫩闭合').describe('阴道状态词（随刺激阶段）：粉嫩闭合→微潮微张→湿亮翕动→湿透抽搐→余韵酸软→红肿泥泞'), 湿润度: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(30), 敏感度: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(50) }).prefault({ 状态: '粉嫩闭合', 湿润度: 30, 敏感度: 50 }),
      肛门: z.object({ 状态: z.string().prefault('浅粉紧致').describe('肛门状态词：浅粉紧致→湿润微松→红肿扩张→余韵收缩') }).prefault({ 状态: '浅粉紧致' }),
      嘴: z.object({ 状态: z.string().prefault('粉润轻抿').describe('嘴状态词：粉润轻抿→微张喘息→唾液拉丝→红肿微肿') }).prefault({ 状态: '粉润轻抿' }),
      肌肤: z.object({ 状态: z.string().prefault('白皙干爽').describe('肌肤状态词：白皙干爽→泛红微汗→绯红发烫→潮红汗湿'), 体温: z.string().prefault('微温').describe('体温词：清凉→微温→发烫→滚烫') }).prefault({ 状态: '白皙干爽', 体温: '微温' }),
      大腿: z.object({ 状态: z.string().prefault('白皙并拢').describe('大腿状态词：白皙并拢→微颤夹紧→泛红轻颤→酸软大开') }).prefault({ 状态: '白皙并拢' }),
      臀部: z.object({ 状态: z.string().prefault('白皙圆润').describe('臀部状态词：白皙圆润→泛红发烫→潮红轻颤→酸软挺翘') }).prefault({ 状态: '白皙圆润' }),
    }).prefault({ 胸部: { 状态: '白皙挺立', 乳头: '淡粉平坦', 敏感度: 50 }, 阴道: { 状态: '粉嫩闭合', 湿润度: 30, 敏感度: 50 }, 肛门: { 状态: '浅粉紧致' }, 嘴: { 状态: '粉润轻抿' }, 肌肤: { 状态: '白皙干爽', 体温: '微温' }, 大腿: { 状态: '白皙并拢' }, 臀部: { 状态: '白皙圆润' } }),
    生理周期: z.object({
      月经日: z.coerce.number().transform(v => _.clamp(v, 0, 28)).prefault(1),
      周期天数: z.coerce.number().transform(v => _.clamp(v, 21, 35)).prefault(28),
      月经状态: z.enum(['经期', '卵泡期', '排卵期', '黄体期']).prefault('卵泡期'),
      经期开始日: z.coerce.number().transform(v => _.clamp(v, 0, 28)).prefault(1),
      怀孕: z.boolean().prefault(false),
      怀孕周数: z.coerce.number().transform(v => _.clamp(v, 0, 42)).prefault(0),
      避孕: z.boolean().prefault(true),
      备孕: z.boolean().prefault(false),
      排卵日: z.coerce.number().transform(v => _.clamp(v, 0, 28)).prefault(14),
    }).prefault({ 月经日: 1, 周期天数: 28, 月经状态: '卵泡期', 经期开始日: 1, 怀孕: false, 怀孕周数: 0, 避孕: true, 备孕: false, 排卵日: 14 }),
    心理状态: z.object({
      欲望度: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(20),
      羞耻感: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(40),
      兴奋: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(10),
      期待: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(10),
      精神状态: z.string().prefault('正常'),
    }).prefault({ 欲望度: 20, 羞耻感: 40, 兴奋: 10, 期待: 10, 精神状态: '正常' }),
    心声: z.string().prefault(''),
  }).prefault({ 身份: '', 省份: '', 方言: '', 关系: '', 好感度: 3, 缴械值: 0, 缴械次数: 0, 战斗次数: 0, 胜场: 0, 败场: 0, 名器: '', 名器防御: 6, 防守值上限: 44, 技能: { 名: '', 等级: 1, 经验: 0, 技能组: {} }, 能力值: { 忍耐: 5, 持久: 5, 反攻: 5 }, 特质: '', 缺陷: '', 欲望积压: 0, 压力值: 50, 是否俘虏: false, 俘虏日期: '', 今日已使用: false, 道具栏: {}, 恢复技能: { 名: '', 等级: 1, 经验: 0 }, 服装: {}, 身体状态: { 胸部: { 状态: '正常', 乳头: '正常', 敏感度: 50 }, 阴道: { 状态: '正常', 湿润度: 30, 敏感度: 50 }, 肛门: { 状态: '正常' }, 嘴: { 状态: '正常' }, 肌肤: { 状态: '正常', 体温: '正常' }, 大腿: { 状态: '正常' }, 臀部: { 状态: '正常' } }, 生理周期: { 月经日: 1, 周期天数: 28, 月经状态: '卵泡期', 经期开始日: 1, 怀孕: false, 怀孕周数: 0, 避孕: true, 备孕: false, 排卵日: 14 }, 心理状态: { 欲望度: 20, 羞耻感: 40, 兴奋: 10, 期待: 10, 精神状态: '正常' }, 心声: '' }).prefault({})),
}).prefault({ 时间: { 日期: '2026年9月1日', 星期: '星期一', 时段: '上午' }, 玩家: { 学业总分: 420, 各科: { 语文: 100, 数学: 85, 英语: 95, 物理: 70, 化学: 80, 生物: 90 }, 技能: { 螺旋: { 等级: 1, 经验: 0 }, 颗粒: { 等级: 1, 经验: 0 }, 敏感度加倍: { 等级: 1, 经验: 0 }, 硬度翻倍: { 等级: 1, 经验: 0 }, 热量翻倍: { 等级: 1, 经验: 0 }, 次数翻倍: { 等级: 1, 经验: 0 }, 频率翻倍: { 等级: 1, 经验: 0 } }, 体力: 80, 性欲: 30, 勃起度: 10, 今日胜场: 0, 今日败场: 0, 累计缴械: 0, 累计被缴械: 0, 道具栏: { 印度神油: 3, 伟哥: 2, 辣椒油: 1, 六神花露水: 1, 清凉油: 0, 润滑液: 2 }, 恢复技能: { 提肛: { 等级: 1, 经验: 0 }, 思维分散: { 等级: 1, 经验: 0 } } }, 排班: { 今日场次: {}, 当前战斗目标: '', 战斗状态: '未开始', 战斗: { 回合: 0, 主角防守值: 96, 主角防守值上限: 96, 她防守值: 44, 她防守值上限: 44, 麻痒点: 0, 主角麻痒点: 0, 她减伤修正: 0, 目标列表: [], 目标防守值: {}, 本场经验: {}, 主角BUFF: {}, 她BUFF: {} } }, 女性角色: {} });

export type Schema = z.output<typeof Schema>;
