export const Schema = z.object({
  时间: z.object({
    日期: z.string().prefault('2026年9月1日'),
    星期: z.string().prefault('星期二'),
    时段: z.enum(['上午', '下午', '晚上', '深夜']).prefault('上午'),
  }).prefault({ 日期: '2026年9月1日', 星期: '星期二', 时段: '上午' }),
  玩家: z.object({
    体力: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(80),
    资金池: z.coerce.number().transform(v => _.clamp(v, 0, 99999999)).prefault(0),
    全网名声: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(0),
    性欲: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(30),
    勃起度: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(10),
  }).prefault({ 体力: 80, 性欲: 30, 勃起度: 10 }),
  当前目标: z.string().prefault(''),
  女主: z.record(z.string().describe('女主名'), z.object({
    身份: z.string().prefault(''),
    丈夫: z.string().prefault(''),
    家庭: z.string().prefault(''),
    名器: z.string().prefault(''),
    技能: z.string().prefault(''),
    吸收量: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(0),
    转化率: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(70),
    掌控值: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(0),
    亲密值: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(0),
    丈夫抵抗: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(70),
    曝光度: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(0),
    案底: z.enum(["", "治安拘留", "刑事立案", "取保候审"]).prefault(""),
    危机状态: z.enum(["", "传唤", "拘留", "立案", "诉讼", "和解", "坐牢"]).prefault(""),
    怀孕: z.enum(['未孕', '孕一月', '孕二月', '孕三月', '孕四月', '孕五月', '孕六月', '孕七月', '孕八月', '临盆']).prefault('未孕'),
    生理: z.object({
      周期天数: z.coerce.number().transform(v => _.clamp(v, 20, 40)).prefault(28),
      周期日: z.coerce.number().transform(v => _.clamp(v, 1, 40)).prefault(1),
      上次月经: z.string().prefault(''),
    }).prefault({ 周期天数: 28, 周期日: 1, 上次月经: '' }),
    阶段: z.coerce.number().transform(v => _.clamp(v, 1, 5)).prefault(1),
    丈夫察觉度: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(0),
    资源转移: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(0),
    决裂: z.boolean().prefault(false),
    火葬场进度: z.enum(['', '傲慢试探', '资源封杀', '认知崩塌', '抛弃一切', '极端强制', '自毁威胁', '替身反噬', '终局退场']).prefault(''),
    专属: z.record(z.string(), z.any()).prefault({}),
    身体状态: z.object({
      胸部: z.object({ 状态: z.string().prefault('正常'), 敏感度: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(50) }).prefault({ 状态: '正常', 敏感度: 50 }),
      阴道: z.object({ 状态: z.string().prefault('正常'), 湿润度: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(30), 敏感度: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(50) }).prefault({ 状态: '正常', 湿润度: 30, 敏感度: 50 }),
      肛门: z.object({ 状态: z.string().prefault('正常') }).prefault({ 状态: '正常' }),
      嘴: z.object({ 状态: z.string().prefault('正常') }).prefault({ 状态: '正常' }),
      肌肤: z.object({ 状态: z.string().prefault('正常'), 体温: z.string().prefault('正常') }).prefault({ 状态: '正常', 体温: '正常' }),
      大腿: z.object({ 状态: z.string().prefault('正常') }).prefault({ 状态: '正常' }),
      臀部: z.object({ 状态: z.string().prefault('正常') }).prefault({ 状态: '正常' }),
    }).prefault({ 胸部: { 状态: '正常', 敏感度: 50 }, 阴道: { 状态: '正常', 湿润度: 30, 敏感度: 50 }, 肛门: { 状态: '正常' }, 嘴: { 状态: '正常' }, 肌肤: { 状态: '正常', 体温: '正常' }, 大腿: { 状态: '正常' }, 臀部: { 状态: '正常' } }),
    心理状态: z.object({
      欲望度: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(20),
      羞耻感: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(40),
      兴奋: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(10),
      依恋: z.coerce.number().transform(v => _.clamp(v, 0, 100)).prefault(10),
      精神状态: z.string().prefault('正常'),
    }).prefault({ 欲望度: 20, 羞耻感: 40, 兴奋: 10, 依恋: 10, 精神状态: '正常' }),
    心声: z.string().prefault(''),
  }).prefault({ 身份: '', 丈夫: '', 家庭: '', 名器: '', 技能: '', 吸收量: 0, 转化率: 70, 掌控值: 0, 亲密值: 0, 丈夫抵抗: 70, 曝光度: 0, 案底: "", 危机状态: "", 怀孕: '未孕', 生理: { 周期天数: 28, 周期日: 1, 上次月经: '' }, 阶段: 1, 丈夫察觉度: 0, 资源转移: 0, 决裂: false, 火葬场进度: '', 专属: {}, 身体状态: { 胸部: { 状态: '正常', 敏感度: 50 }, 阴道: { 状态: '正常', 湿润度: 30, 敏感度: 50 }, 肛门: { 状态: '正常' }, 嘴: { 状态: '正常' }, 肌肤: { 状态: '正常', 体温: '正常' }, 大腿: { 状态: '正常' }, 臀部: { 状态: '正常' } }, 心理状态: { 欲望度: 20, 羞耻感: 40, 兴奋: 10, 依恋: 10, 精神状态: '正常' }, 心声: '' }).prefault({})),
}).prefault({ 时间: { 日期: '2026年9月1日', 星期: '星期二', 时段: '上午' }, 玩家: { 体力: 80, 性欲: 30, 勃起度: 10 }, 当前目标: '', 女主: {} });

export type Schema = z.output<typeof Schema>;
