import fs from 'fs';
const card = JSON.parse(fs.readFileSync('src/欲望都市/欲望都市.json','utf8'));
const d = card.data;
console.log('creator:', JSON.stringify(d.creator));
console.log('creator_notes len:', d.creator_notes?.length);
console.log('character_version:', JSON.stringify(d.character_version));
console.log('system_prompt len:', d.system_prompt?.length);
console.log('post_history_instructions len:', d.post_history_instructions?.length);
console.log('description len:', d.description?.length);
console.log('personality len:', d.personality?.length);
console.log('scenario len:', d.scenario?.length);
console.log('mes_example len:', d.mes_example?.length);
console.log('alternate_greetings:', (d.alternate_greetings||[]).length);
console.log('tags:', JSON.stringify(d.tags));
console.log('talkativeness:', d.talkativeness, 'fav:', d.fav);
console.log('avatar present:', !!card.avatar, 'avatar len:', (card.avatar||'').length);
console.log('-- top card fields --');
console.log('top description len:', (card.description||'').length);
console.log('top personality len:', (card.personality||'').length);
console.log('top scenario len:', (card.scenario||'').length);
console.log('top first_mes len:', (card.first_mes||'').length);
console.log('top mes_example len:', (card.mes_example||'').length);
console.log('top alternate_greetings:', (card.alternate_greetings||[]).length);
